// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `<footer data-elementor-type="footer" data-elementor-id="478" class="elementor elementor-478 elementor-location-footer" data-elementor-post-type="elementor_library">
					<section class="elementor-section elementor-top-section elementor-element elementor-element-ed8cdd9 elementor-section-boxed elementor-section-height-default" data-id="ed8cdd9" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-1ac23b5" data-id="1ac23b5" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0e32c0f elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-hidden-desktop elementor-hidden-tablet elementor-widget elementor-widget-theme-site-logo elementor-widget-image" data-id="0e32c0f" data-element_type="widget" data-e-type="widget" data-widget_type="theme-site-logo.default">
				<div class="elementor-widget-container">
											<a href="/">
			<img width="133" height="38" src="/images/cropped-logo.png" class="attachment-full size-full wp-image-4737" alt="">				</a>
											</div>
				</div>
				<div class="elementor-element elementor-element-ba43388 elementor-hidden-desktop elementor-hidden-tablet elementor-widget elementor-widget-text-editor" data-id="ba43388" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat.								</div>
				</div>
				<div class="elementor-element elementor-element-6472565 elementor-widget elementor-widget-heading" data-id="6472565" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h4 class="elementor-heading-title elementor-size-default">Stay in the loop</h4>				</div>
				</div>
				<div class="elementor-element elementor-element-5b1f80c elementor-button-align-start elementor-mobile-button-align-stretch elementor-widget elementor-widget-form" data-id="5b1f80c" data-element_type="widget" data-e-type="widget" data-settings="{&quot;button_width&quot;:&quot;25&quot;,&quot;step_type&quot;:&quot;number_text&quot;,&quot;step_icon_shape&quot;:&quot;circle&quot;}" data-widget_type="form.default">
				<div class="elementor-widget-container">
							<form class="elementor-form" method="post" name="New Form" aria-label="New Form">
			<input type="hidden" name="post_id" value="478">
			<input type="hidden" name="form_id" value="5b1f80c">
			<input type="hidden" name="referer_title" value="Top 10 NFT projects that shocked the Internet with their uniqueness">

							<input type="hidden" name="queried_id" value="70">
			
			<div class="elementor-form-fields-wrapper elementor-labels-">
								<div class="elementor-field-type-email elementor-field-group elementor-column elementor-field-group-email elementor-col-75 elementor-md-100 elementor-field-required">
												<label for="form-field-email" class="elementor-field-label elementor-screen-only">
								Email							</label>
														<input size="1" type="email" name="form_fields[email]" id="form-field-email" class="elementor-field elementor-size-sm  elementor-field-textual" placeholder="Email here..." required="required">
											</div>
								<div class="elementor-field-group elementor-column elementor-field-type-submit elementor-col-25 e-form__buttons">
					<button class="elementor-button elementor-size-sm elementor-animation-push" type="submit">
						<span class="elementor-button-content-wrapper">
																						<span class="elementor-button-text">Subscribe</span>
													</span>
					</button>
				</div>
			</div>
		</form>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-4b33557" data-id="4b33557" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-6c06eec elementor-widget elementor-widget-heading" data-id="6c06eec" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h4 class="elementor-heading-title elementor-size-default">Join the community</h4>				</div>
				</div>
				<div class="elementor-element elementor-element-851abec e-grid-align-left elementor-grid-tablet-0 elementor-shape-rounded elementor-grid-0 elementor-widget elementor-widget-social-icons" data-id="851abec" data-element_type="widget" data-e-type="widget" data-widget_type="social-icons.default">
				<div class="elementor-widget-container">
							<div class="elementor-social-icons-wrapper elementor-grid" role="list">
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-twitter elementor-repeater-item-56ed774" target="_blank">
						<span class="elementor-screen-only">Twitter</span>
						<i aria-hidden="true" class="fab fa-twitter"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-facebook-f elementor-repeater-item-75c5971" target="_blank">
						<span class="elementor-screen-only">Facebook-f</span>
						<i aria-hidden="true" class="fab fa-facebook-f"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-instagram elementor-repeater-item-021326e" target="_blank">
						<span class="elementor-screen-only">Instagram</span>
						<i aria-hidden="true" class="fab fa-instagram"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-youtube elementor-repeater-item-71cdd6a" target="_blank">
						<span class="elementor-screen-only">Youtube</span>
						<i aria-hidden="true" class="fab fa-youtube"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-linkedin-in elementor-repeater-item-a0296bf" target="_blank">
						<span class="elementor-screen-only">Linkedin-in</span>
						<i aria-hidden="true" class="fab fa-linkedin-in"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-telegram-plane elementor-repeater-item-934ac1c" target="_blank">
						<span class="elementor-screen-only">Telegram-plane</span>
						<i aria-hidden="true" class="fab fa-telegram-plane"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-discord elementor-repeater-item-6f3d2bf" target="_blank">
						<span class="elementor-screen-only">Discord</span>
						<i aria-hidden="true" class="fab fa-discord"></i>					</a>
				</span>
					</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-957b0b5 elementor-section-boxed elementor-section-height-default" data-id="957b0b5" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-b9d4667 elementor-hidden-mobile" data-id="b9d4667" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-cbd1282 elementor-widget__width-auto elementor-widget elementor-widget-theme-site-logo elementor-widget-image" data-id="cbd1282" data-element_type="widget" data-e-type="widget" data-widget_type="theme-site-logo.default">
				<div class="elementor-widget-container">
											<a href="/">
			<img width="133" height="38" src="/images/cropped-logo.png" class="attachment-full size-full wp-image-4737" alt="">				</a>
											</div>
				</div>
				<div class="elementor-element elementor-element-6845233 elementor-widget elementor-widget-text-editor" data-id="6845233" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat.								</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-3891228" data-id="3891228" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-dc371ad elementor-section-boxed elementor-section-height-default" data-id="dc371ad" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-45d552d" data-id="45d552d" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-988d370 elementor-widget elementor-widget-heading" data-id="988d370" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">My account</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-5f3d16b elementor-nav-menu__align-start elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu" data-id="5f3d16b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;layout&quot;:&quot;vertical&quot;,&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;&quot;}}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-vertical e--pointer-text e--animation-none">
				<ul id="menu-1-5f3d16b" class="elementor-nav-menu sm-vertical" data-smartmenus-id="17794472358371973"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1003"><a href="#" class="elementor-item elementor-item-anchor">Profile</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1004"><a href="#" class="elementor-item elementor-item-anchor">My Collections</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1005"><a href="#" class="elementor-item elementor-item-anchor">Create item</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1006"><a href="#" class="elementor-item elementor-item-anchor">Settings</a></li>
</ul>			</nav>
						<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true" style="--menu-height: 0;">
				<ul id="menu-2-5f3d16b" class="elementor-nav-menu sm-vertical" data-smartmenus-id="17794472358379932"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1003"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Profile</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1004"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">My Collections</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1005"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Create item</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1006"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Settings</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-d7d446c" data-id="d7d446c" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-99a1659 elementor-widget elementor-widget-heading" data-id="99a1659" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Resources</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-866765b elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu" data-id="866765b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;layout&quot;:&quot;vertical&quot;,&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;&quot;}}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-vertical e--pointer-text e--animation-none">
				<ul id="menu-1-866765b" class="elementor-nav-menu sm-vertical" data-smartmenus-id="17794472358386316"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1007"><a href="#" class="elementor-item elementor-item-anchor">Help center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1008"><a href="#" class="elementor-item elementor-item-anchor">Partners</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1009"><a href="#" class="elementor-item elementor-item-anchor">Activity</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1010"><a href="#" class="elementor-item elementor-item-anchor">Rankings</a></li>
</ul>			</nav>
						<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true" style="--menu-height: 0;">
				<ul id="menu-2-866765b" class="elementor-nav-menu sm-vertical" data-smartmenus-id="17794472358390186"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1007"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Help center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1008"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Partners</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1009"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Activity</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1010"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Rankings</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-610acff" data-id="610acff" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-68fe9c4 elementor-widget elementor-widget-heading" data-id="68fe9c4" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Company</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-541a2bf elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu" data-id="541a2bf" data-element_type="widget" data-e-type="widget" data-settings="{&quot;layout&quot;:&quot;vertical&quot;,&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;&quot;}}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-vertical e--pointer-text e--animation-none">
				<ul id="menu-1-541a2bf" class="elementor-nav-menu sm-vertical" data-smartmenus-id="1779447235839054"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1012"><a href="#" class="elementor-item elementor-item-anchor">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1011"><a href="#" class="elementor-item elementor-item-anchor">Careers</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1013"><a href="#" class="elementor-item elementor-item-anchor">Blog</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1014"><a href="#" class="elementor-item elementor-item-anchor">Contact us</a></li>
</ul>			</nav>
						<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true" style="--menu-height: 0;">
				<ul id="menu-2-541a2bf" class="elementor-nav-menu sm-vertical" data-smartmenus-id="17794472358408787"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1012"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1011"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Careers</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1013"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Blog</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1014"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Contact us</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-7890a5e elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="7890a5e" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-ad59622" data-id="ad59622" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-468a146 elementor-widget elementor-widget-heading" data-id="468a146" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<div class="elementor-heading-title elementor-size-default">Merkulove © 2022 Xchain template. All rights reserved.</div>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-14c5633" data-id="14c5633" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-9643ef5 elementor-widget elementor-widget-heading" data-id="9643ef5" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<div class="elementor-heading-title elementor-size-default">Privacy policy  |  Terms of service</div>				</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				</footer>`;
