// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `<header data-elementor-type="header" data-elementor-id="80" class="elementor elementor-80 elementor-location-header" data-elementor-post-type="elementor_library">
					<section class="elementor-section elementor-top-section elementor-element elementor-element-e2ac055 elementor-section-content-middle elementor-hidden-tablet elementor-hidden-mobile elementor-section-boxed elementor-section-height-default elementor-sticky elementor-sticky--active elementor-section--handles-inside elementor-sticky--effects" data-id="e2ac055" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;sticky&quot;:&quot;top&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false,&quot;sticky_on&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;sticky_offset&quot;:0,&quot;sticky_effects_offset&quot;:0,&quot;sticky_anchor_link_offset&quot;:0}" style="position: fixed; width: 100%; margin-top: 0px; margin-bottom: 0px; top: 0px;">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-621bb0f" data-id="621bb0f" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-fd7c80f elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="fd7c80f" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-9daa1a0" data-id="9daa1a0" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-907b95e elementor-widget elementor-widget-theme-site-logo elementor-widget-image" data-id="907b95e" data-element_type="widget" data-e-type="widget" data-widget_type="theme-site-logo.default">
				<div class="elementor-widget-container">
											<a href="/">
			<img width="133" height="38" src="/images/cropped-logo.png" class="attachment-thumbnail size-thumbnail wp-image-4737" alt="">				</a>
											</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-aae9ab4" data-id="aae9ab4" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-6282b8b elementor-search-form--skin-minimal elementor-widget elementor-widget-search-form" data-id="6282b8b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;skin&quot;:&quot;minimal&quot;}" data-widget_type="search-form.default">
				<div class="elementor-widget-container">
							<search role="search">
			<form class="elementor-search-form" action="#" method="get">
												<div class="elementor-search-form__container">
					<label class="elementor-screen-only" for="elementor-search-form-6282b8b">Search</label>

											<div class="elementor-search-form__icon">
							<i aria-hidden="true" class="fas fa-search"></i>							<span class="elementor-screen-only">Search</span>
						</div>
					
					<input id="elementor-search-form-6282b8b" placeholder="Search items, collection or user" class="elementor-search-form__input" type="search" name="s" value="">
					
					
									</div>
			</form>
		</search>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-4eefed0" data-id="4eefed0" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-19baa61 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="19baa61" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-fce539c" data-id="fce539c" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-1eeb09b elementor-widget__width-auto elementor-nav-menu__align-end elementor-nav-menu--dropdown-tablet elementor-nav-menu__text-align-aside elementor-nav-menu--toggle elementor-nav-menu--burger elementor-widget elementor-widget-nav-menu" data-id="1eeb09b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;fas fa-angle-down\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;fa-solid&quot;},&quot;layout&quot;:&quot;horizontal&quot;,&quot;toggle&quot;:&quot;burger&quot;}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-horizontal e--pointer-underline e--animation-fade">
				<ul id="menu-1-1eeb09b" class="elementor-nav-menu" data-smartmenus-id="17794472358314048"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5548 current_page_item menu-item-has-children menu-item-5551"><a href="/" aria-current="page" class="elementor-item elementor-item-active has-submenu" id="sm-17794472358314048-1" aria-haspopup="true" aria-controls="sm-17794472358314048-2" aria-expanded="false">Home<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-17794472358314048-2" role="group" aria-hidden="true" aria-labelledby="sm-17794472358314048-1" aria-expanded="false">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-370"><a href="/home-2" class="elementor-sub-item">Home 2</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-has-children menu-item-4982"><a href="/shop" class="elementor-item has-submenu" id="sm-17794472358314048-3" aria-haspopup="true" aria-controls="sm-17794472358314048-4" aria-expanded="false">Shop<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-17794472358314048-4" role="group" aria-hidden="true" aria-labelledby="sm-17794472358314048-3" aria-expanded="false">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-5552"><a href="/shop-2" class="elementor-sub-item">Shop 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-product menu-item-1657"><a href="/product" class="elementor-sub-item">Single product</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-373"><a href="#" class="elementor-item elementor-item-anchor has-submenu" id="sm-17794472358314048-5" aria-haspopup="true" aria-controls="sm-17794472358314048-6" aria-expanded="false">Pages<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-17794472358314048-6" role="group" aria-hidden="true" aria-labelledby="sm-17794472358314048-5" aria-expanded="false">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4470"><a href="/about" class="elementor-sub-item">About</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377"><a href="/about" class="elementor-sub-item">Help center</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4471"><a href="/authors" class="elementor-sub-item">Team</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6168"><a href="/authors" class="elementor-sub-item">Authors</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4474"><a href="/login" class="elementor-sub-item">Login</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4467"><a href="/404" class="elementor-sub-item">Error page</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-4696"><a href="/blog" class="elementor-item has-submenu" id="sm-17794472358314048-7" aria-haspopup="true" aria-controls="sm-17794472358314048-8" aria-expanded="false">Blog<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-17794472358314048-8" role="group" aria-hidden="true" aria-labelledby="sm-17794472358314048-7" aria-expanded="false">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4697"><a href="/blog-2" class="elementor-sub-item">Blog 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1281"><a href="/blog" class="elementor-sub-item">Single post</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-375"><a href="/contacts" class="elementor-item">Contacts</a></li>
</ul>			</nav>
					<div class="elementor-menu-toggle" role="button" tabindex="0" aria-label="Menu Toggle" aria-expanded="false">
			<i aria-hidden="true" role="presentation" class="elementor-menu-toggle__icon--open eicon-menu-bar"></i><i aria-hidden="true" role="presentation" class="elementor-menu-toggle__icon--close eicon-close"></i>		</div>
					<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true" style="--menu-height: 0;">
				<ul id="menu-2-1eeb09b" class="elementor-nav-menu" data-smartmenus-id="1779447235835235"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5548 current_page_item menu-item-has-children menu-item-5551"><a href="/" aria-current="page" class="elementor-item elementor-item-active has-submenu" tabindex="-1" id="sm-1779447235835235-1" aria-haspopup="true" aria-controls="sm-1779447235835235-2" aria-expanded="false">Home<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-1779447235835235-2" role="group" aria-hidden="true" aria-labelledby="sm-1779447235835235-1" aria-expanded="false">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-370"><a href="/home-2" class="elementor-sub-item" tabindex="-1">Home 2</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-has-children menu-item-4982"><a href="/shop" class="elementor-item has-submenu" tabindex="-1" id="sm-1779447235835235-3" aria-haspopup="true" aria-controls="sm-1779447235835235-4" aria-expanded="false">Shop<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-1779447235835235-4" role="group" aria-hidden="true" aria-labelledby="sm-1779447235835235-3" aria-expanded="false">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-5552"><a href="/shop-2" class="elementor-sub-item" tabindex="-1">Shop 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-product menu-item-1657"><a href="/product" class="elementor-sub-item" tabindex="-1">Single product</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-373"><a href="#" class="elementor-item elementor-item-anchor has-submenu" tabindex="-1" id="sm-1779447235835235-5" aria-haspopup="true" aria-controls="sm-1779447235835235-6" aria-expanded="false">Pages<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-1779447235835235-6" role="group" aria-hidden="true" aria-labelledby="sm-1779447235835235-5" aria-expanded="false">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4470"><a href="/about" class="elementor-sub-item" tabindex="-1">About</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377"><a href="/about" class="elementor-sub-item" tabindex="-1">Help center</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4471"><a href="/authors" class="elementor-sub-item" tabindex="-1">Team</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6168"><a href="/authors" class="elementor-sub-item" tabindex="-1">Authors</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4474"><a href="/login" class="elementor-sub-item" tabindex="-1">Login</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4467"><a href="/404" class="elementor-sub-item" tabindex="-1">Error page</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-4696"><a href="/blog" class="elementor-item has-submenu" tabindex="-1" id="sm-1779447235835235-7" aria-haspopup="true" aria-controls="sm-1779447235835235-8" aria-expanded="false">Blog<span class="sub-arrow"><i class="fas fa-angle-down" aria-hidden="true"></i></span></a>
<ul class="sub-menu elementor-nav-menu--dropdown" id="sm-1779447235835235-8" role="group" aria-hidden="true" aria-labelledby="sm-1779447235835235-7" aria-expanded="false">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4697"><a href="/blog-2" class="elementor-sub-item" tabindex="-1">Blog 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1281"><a href="/blog" class="elementor-sub-item" tabindex="-1">Single post</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-375"><a href="/contacts" class="elementor-item" tabindex="-1">Contacts</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-f0c7eb3" data-id="f0c7eb3" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0175cca elementor-widget__width-auto elementor-widget elementor-widget-button" data-id="0175cca" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Connect wallet</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section><section class="elementor-section elementor-top-section elementor-element elementor-element-e2ac055 elementor-section-content-middle elementor-hidden-tablet elementor-hidden-mobile elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-sticky elementor-sticky__spacer" data-id="e2ac055" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;sticky&quot;:&quot;top&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false,&quot;sticky_on&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;sticky_offset&quot;:0,&quot;sticky_effects_offset&quot;:0,&quot;sticky_anchor_link_offset&quot;:0}" style="visibility: hidden; transition: none; animation: auto ease 0s 1 normal none running none;">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-621bb0f" data-id="621bb0f" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-fd7c80f elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="fd7c80f" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-9daa1a0" data-id="9daa1a0" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-907b95e elementor-widget elementor-widget-theme-site-logo elementor-widget-image" data-id="907b95e" data-element_type="widget" data-e-type="widget" data-widget_type="theme-site-logo.default">
				<div class="elementor-widget-container">
											<a href="/">
			<img width="133" height="38" src="/images/cropped-logo.png" class="attachment-thumbnail size-thumbnail wp-image-4737" alt="">				</a>
											</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-aae9ab4" data-id="aae9ab4" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-6282b8b elementor-search-form--skin-minimal elementor-widget elementor-widget-search-form" data-id="6282b8b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;skin&quot;:&quot;minimal&quot;}" data-widget_type="search-form.default">
				<div class="elementor-widget-container">
							<search role="search">
			<form class="elementor-search-form" action="#" method="get">
												<div class="elementor-search-form__container">
					<label class="elementor-screen-only" for="elementor-search-form-6282b8b">Search</label>

											<div class="elementor-search-form__icon">
							<i aria-hidden="true" class="fas fa-search"></i>							<span class="elementor-screen-only">Search</span>
						</div>
					
					<input id="elementor-search-form-6282b8b" placeholder="Search items, collection or user" class="elementor-search-form__input" type="search" name="s" value="">
					
					
									</div>
			</form>
		</search>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-4eefed0" data-id="4eefed0" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-19baa61 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="19baa61" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-fce539c" data-id="fce539c" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-1eeb09b elementor-widget__width-auto elementor-nav-menu__align-end elementor-nav-menu--dropdown-tablet elementor-nav-menu__text-align-aside elementor-nav-menu--toggle elementor-nav-menu--burger elementor-widget elementor-widget-nav-menu" data-id="1eeb09b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;fas fa-angle-down\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;fa-solid&quot;},&quot;layout&quot;:&quot;horizontal&quot;,&quot;toggle&quot;:&quot;burger&quot;}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-horizontal e--pointer-underline e--animation-fade">
				<ul id="menu-1-1eeb09b" class="elementor-nav-menu"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5548 current_page_item menu-item-has-children menu-item-5551"><a href="/" aria-current="page" class="elementor-item elementor-item-active">Home</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-370"><a href="/home-2" class="elementor-sub-item">Home 2</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-has-children menu-item-4982"><a href="/shop" class="elementor-item">Shop</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-5552"><a href="/shop-2" class="elementor-sub-item">Shop 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-product menu-item-1657"><a href="/product" class="elementor-sub-item">Single product</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-373"><a href="#" class="elementor-item elementor-item-anchor">Pages</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4470"><a href="/about" class="elementor-sub-item">About</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377"><a href="/about" class="elementor-sub-item">Help center</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4471"><a href="/authors" class="elementor-sub-item">Team</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6168"><a href="/authors" class="elementor-sub-item">Authors</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4474"><a href="/login" class="elementor-sub-item">Login</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4467"><a href="/404" class="elementor-sub-item">Error page</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-4696"><a href="/blog" class="elementor-item">Blog</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4697"><a href="/blog-2" class="elementor-sub-item">Blog 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1281"><a href="/blog" class="elementor-sub-item">Single post</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-375"><a href="/contacts" class="elementor-item">Contacts</a></li>
</ul>			</nav>
					<div class="elementor-menu-toggle" role="button" tabindex="0" aria-label="Menu Toggle" aria-expanded="false">
			<i aria-hidden="true" role="presentation" class="elementor-menu-toggle__icon--open eicon-menu-bar"></i><i aria-hidden="true" role="presentation" class="elementor-menu-toggle__icon--close eicon-close"></i>		</div>
					<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true">
				<ul id="menu-2-1eeb09b" class="elementor-nav-menu"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5548 current_page_item menu-item-has-children menu-item-5551"><a href="/" aria-current="page" class="elementor-item elementor-item-active" tabindex="-1">Home</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-370"><a href="/home-2" class="elementor-sub-item" tabindex="-1">Home 2</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-has-children menu-item-4982"><a href="/shop" class="elementor-item" tabindex="-1">Shop</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-5552"><a href="/shop-2" class="elementor-sub-item" tabindex="-1">Shop 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-product menu-item-1657"><a href="/product" class="elementor-sub-item" tabindex="-1">Single product</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-373"><a href="#" class="elementor-item elementor-item-anchor" tabindex="-1">Pages</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4470"><a href="/about" class="elementor-sub-item" tabindex="-1">About</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377"><a href="/about" class="elementor-sub-item" tabindex="-1">Help center</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4471"><a href="/authors" class="elementor-sub-item" tabindex="-1">Team</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6168"><a href="/authors" class="elementor-sub-item" tabindex="-1">Authors</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4474"><a href="/login" class="elementor-sub-item" tabindex="-1">Login</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4467"><a href="/404" class="elementor-sub-item" tabindex="-1">Error page</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-4696"><a href="/blog" class="elementor-item" tabindex="-1">Blog</a>
<ul class="sub-menu elementor-nav-menu--dropdown">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4697"><a href="/blog-2" class="elementor-sub-item" tabindex="-1">Blog 2</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1281"><a href="/blog" class="elementor-sub-item" tabindex="-1">Single post</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-375"><a href="/contacts" class="elementor-item" tabindex="-1">Contacts</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-f0c7eb3" data-id="f0c7eb3" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0175cca elementor-widget__width-auto elementor-widget elementor-widget-button" data-id="0175cca" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Connect wallet</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-bcbe4c3 elementor-section-content-middle elementor-hidden-desktop elementor-hidden-mobile elementor-section-full_width elementor-section-height-default elementor-sticky elementor-sticky--active elementor-section--handles-inside elementor-sticky--effects" data-id="bcbe4c3" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;sticky&quot;:&quot;top&quot;,&quot;sticky_offset_tablet&quot;:0,&quot;sticky_effects_offset_tablet&quot;:0,&quot;mdp_selection_sticky_effect_enable&quot;:false,&quot;sticky_on&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;sticky_offset&quot;:0,&quot;sticky_effects_offset&quot;:0,&quot;sticky_anchor_link_offset&quot;:0}" style="position: fixed; margin-top: 0px; margin-bottom: 0px; top: 0px;">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-731d54f" data-id="731d54f" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e7394a2 elementor-widget__width-auto elementor-widget elementor-widget-theme-site-logo elementor-widget-image" data-id="e7394a2" data-element_type="widget" data-e-type="widget" data-widget_type="theme-site-logo.default">
				<div class="elementor-widget-container">
											<a href="/">
			<img width="133" height="38" src="/images/cropped-logo.png" class="attachment-thumbnail size-thumbnail wp-image-4737" alt="">				</a>
											</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-ad578a2" data-id="ad578a2" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2f88488 elementor-search-form--skin-minimal elementor-widget elementor-widget-search-form" data-id="2f88488" data-element_type="widget" data-e-type="widget" data-settings="{&quot;skin&quot;:&quot;minimal&quot;}" data-widget_type="search-form.default">
				<div class="elementor-widget-container">
							<search role="search">
			<form class="elementor-search-form" action="#" method="get">
												<div class="elementor-search-form__container">
					<label class="elementor-screen-only" for="elementor-search-form-2f88488">Search</label>

											<div class="elementor-search-form__icon">
							<i aria-hidden="true" class="fas fa-search"></i>							<span class="elementor-screen-only">Search</span>
						</div>
					
					<input id="elementor-search-form-2f88488" placeholder="Search items, collection or user" class="elementor-search-form__input" type="search" name="s" value="">
					
					
									</div>
			</form>
		</search>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-84d6087" data-id="84d6087" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-1aa0967 elementor-widget__width-auto elementor-widget elementor-widget-button" data-id="1aa0967" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Connect</span>
					</span>
					</a>
				</div>
								</div>
				</div>
				<div class="elementor-element elementor-element-a991583 elementor-widget-mobile__width-auto elementor-widget-tablet__width-auto elementor-view-default elementor-widget elementor-widget-icon" data-id="a991583" data-element_type="widget" data-e-type="widget" data-widget_type="icon.default">
				<div class="elementor-widget-container">
							<div class="elementor-icon-wrapper">
			<a class="elementor-icon" href="#">
			<i aria-hidden="true" class="fas fa-bars"></i>			</a>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section><section class="elementor-section elementor-top-section elementor-element elementor-element-bcbe4c3 elementor-section-content-middle elementor-hidden-desktop elementor-hidden-mobile elementor-section-full_width elementor-section-height-default elementor-section-height-default elementor-sticky elementor-sticky__spacer" data-id="bcbe4c3" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;sticky&quot;:&quot;top&quot;,&quot;sticky_offset_tablet&quot;:0,&quot;sticky_effects_offset_tablet&quot;:0,&quot;mdp_selection_sticky_effect_enable&quot;:false,&quot;sticky_on&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;sticky_offset&quot;:0,&quot;sticky_effects_offset&quot;:0,&quot;sticky_anchor_link_offset&quot;:0}" style="visibility: hidden; transition: none; animation: auto ease 0s 1 normal none running none;">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-731d54f" data-id="731d54f" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e7394a2 elementor-widget__width-auto elementor-widget elementor-widget-theme-site-logo elementor-widget-image" data-id="e7394a2" data-element_type="widget" data-e-type="widget" data-widget_type="theme-site-logo.default">
				<div class="elementor-widget-container">
											<a href="/">
			<img width="133" height="38" src="/images/cropped-logo.png" class="attachment-thumbnail size-thumbnail wp-image-4737" alt="">				</a>
											</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-ad578a2" data-id="ad578a2" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2f88488 elementor-search-form--skin-minimal elementor-widget elementor-widget-search-form" data-id="2f88488" data-element_type="widget" data-e-type="widget" data-settings="{&quot;skin&quot;:&quot;minimal&quot;}" data-widget_type="search-form.default">
				<div class="elementor-widget-container">
							<search role="search">
			<form class="elementor-search-form" action="#" method="get">
												<div class="elementor-search-form__container">
					<label class="elementor-screen-only" for="elementor-search-form-2f88488">Search</label>

											<div class="elementor-search-form__icon">
							<i aria-hidden="true" class="fas fa-search"></i>							<span class="elementor-screen-only">Search</span>
						</div>
					
					<input id="elementor-search-form-2f88488" placeholder="Search items, collection or user" class="elementor-search-form__input" type="search" name="s" value="">
					
					
									</div>
			</form>
		</search>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-84d6087" data-id="84d6087" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-1aa0967 elementor-widget__width-auto elementor-widget elementor-widget-button" data-id="1aa0967" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Connect</span>
					</span>
					</a>
				</div>
								</div>
				</div>
				<div class="elementor-element elementor-element-a991583 elementor-widget-mobile__width-auto elementor-widget-tablet__width-auto elementor-view-default elementor-widget elementor-widget-icon" data-id="a991583" data-element_type="widget" data-e-type="widget" data-widget_type="icon.default">
				<div class="elementor-widget-container">
							<div class="elementor-icon-wrapper">
			<a class="elementor-icon" href="#">
			<i aria-hidden="true" class="fas fa-bars"></i>			</a>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-3ec5e72 elementor-section-content-middle elementor-hidden-desktop elementor-hidden-tablet elementor-section-boxed elementor-section-height-default elementor-sticky elementor-sticky--active elementor-section--handles-inside elementor-sticky--effects" data-id="3ec5e72" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;sticky&quot;:&quot;top&quot;,&quot;sticky_offset_mobile&quot;:0,&quot;sticky_effects_offset_mobile&quot;:0,&quot;mdp_selection_sticky_effect_enable&quot;:false,&quot;sticky_on&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;sticky_offset&quot;:0,&quot;sticky_effects_offset&quot;:0,&quot;sticky_anchor_link_offset&quot;:0}" style="position: fixed; margin-top: 0px; margin-bottom: 0px; top: 0px;">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-336ba08" data-id="336ba08" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div data-ep-wrapper-link="{&quot;url&quot;:&quot;index.html&quot;,&quot;is_external&quot;:&quot;&quot;,&quot;nofollow&quot;:&quot;&quot;,&quot;custom_attributes&quot;:&quot;&quot;}" style="cursor: pointer" class="bdt-element-link elementor-element elementor-element-dc1ec9a elementor-widget elementor-widget-image" data-id="dc1ec9a" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img width="38" height="38" src="/images/logo_mobile.png" class="attachment-thumbnail size-thumbnail wp-image-3735" alt="">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-6993590" data-id="6993590" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e33eb2a elementor-search-form--skin-full_screen elementor-widget-mobile__width-auto elementor-widget elementor-widget-search-form" data-id="e33eb2a" data-element_type="widget" data-e-type="widget" data-settings="{&quot;skin&quot;:&quot;full_screen&quot;}" data-widget_type="search-form.default">
				<div class="elementor-widget-container">
							<search role="search">
			<form class="elementor-search-form" action="#" method="get">
												<div class="elementor-search-form__toggle" role="button" tabindex="0" aria-label="Search">
					<i aria-hidden="true" class="fas fa-search"></i>				</div>
								<div class="elementor-search-form__container">
					<label class="elementor-screen-only" for="elementor-search-form-e33eb2a">Search</label>

					
					<input id="elementor-search-form-e33eb2a" placeholder="Search..." class="elementor-search-form__input" type="search" name="s" value="">
					
					
										<div class="dialog-lightbox-close-button dialog-close-button" role="button" tabindex="0" aria-label="Close this search box.">
						<i aria-hidden="true" class="eicon-close"></i>					</div>
									</div>
			</form>
		</search>
						</div>
				</div>
				<div class="elementor-element elementor-element-a849344 elementor-widget__width-auto elementor-widget elementor-widget-button" data-id="a849344" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Connect</span>
					</span>
					</a>
				</div>
								</div>
				</div>
				<div class="elementor-element elementor-element-b40339f elementor-widget-mobile__width-auto elementor-view-default elementor-widget elementor-widget-icon" data-id="b40339f" data-element_type="widget" data-e-type="widget" data-widget_type="icon.default">
				<div class="elementor-widget-container">
							<div class="elementor-icon-wrapper">
			<a class="elementor-icon" href="#">
			<i aria-hidden="true" class="fas fa-bars"></i>			</a>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section><section class="elementor-section elementor-top-section elementor-element elementor-element-3ec5e72 elementor-section-content-middle elementor-hidden-desktop elementor-hidden-tablet elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-sticky elementor-sticky__spacer" data-id="3ec5e72" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;sticky&quot;:&quot;top&quot;,&quot;sticky_offset_mobile&quot;:0,&quot;sticky_effects_offset_mobile&quot;:0,&quot;mdp_selection_sticky_effect_enable&quot;:false,&quot;sticky_on&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;sticky_offset&quot;:0,&quot;sticky_effects_offset&quot;:0,&quot;sticky_anchor_link_offset&quot;:0}" style="visibility: hidden; transition: none; animation: auto ease 0s 1 normal none running none;">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-336ba08" data-id="336ba08" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div data-ep-wrapper-link="{&quot;url&quot;:&quot;index.html&quot;,&quot;is_external&quot;:&quot;&quot;,&quot;nofollow&quot;:&quot;&quot;,&quot;custom_attributes&quot;:&quot;&quot;}" style="cursor: pointer" class="bdt-element-link elementor-element elementor-element-dc1ec9a elementor-widget elementor-widget-image" data-id="dc1ec9a" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img width="38" height="38" src="/images/logo_mobile.png" class="attachment-thumbnail size-thumbnail wp-image-3735" alt="">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-6993590" data-id="6993590" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e33eb2a elementor-search-form--skin-full_screen elementor-widget-mobile__width-auto elementor-widget elementor-widget-search-form" data-id="e33eb2a" data-element_type="widget" data-e-type="widget" data-settings="{&quot;skin&quot;:&quot;full_screen&quot;}" data-widget_type="search-form.default">
				<div class="elementor-widget-container">
							<search role="search">
			<form class="elementor-search-form" action="#" method="get">
												<div class="elementor-search-form__toggle" role="button" tabindex="0" aria-label="Search">
					<i aria-hidden="true" class="fas fa-search"></i>				</div>
								<div class="elementor-search-form__container">
					<label class="elementor-screen-only" for="elementor-search-form-e33eb2a">Search</label>

					
					<input id="elementor-search-form-e33eb2a" placeholder="Search..." class="elementor-search-form__input" type="search" name="s" value="">
					
					
										<div class="dialog-lightbox-close-button dialog-close-button" role="button" tabindex="0" aria-label="Close this search box.">
						<i aria-hidden="true" class="eicon-close"></i>					</div>
									</div>
			</form>
		</search>
						</div>
				</div>
				<div class="elementor-element elementor-element-a849344 elementor-widget__width-auto elementor-widget elementor-widget-button" data-id="a849344" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Connect</span>
					</span>
					</a>
				</div>
								</div>
				</div>
				<div class="elementor-element elementor-element-b40339f elementor-widget-mobile__width-auto elementor-view-default elementor-widget elementor-widget-icon" data-id="b40339f" data-element_type="widget" data-e-type="widget" data-widget_type="icon.default">
				<div class="elementor-widget-container">
							<div class="elementor-icon-wrapper">
			<a class="elementor-icon" href="#">
			<i aria-hidden="true" class="fas fa-bars"></i>			</a>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				</header>`;
