// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `
		
<main id="content" class="site-main post-411 envato_tk_templates type-envato_tk_templates status-publish has-post-thumbnail hentry">

	
	<div class="page-content">
				<div data-elementor-type="wp-post" data-elementor-id="411" class="elementor elementor-411" data-elementor-post-type="envato_tk_templates">
						<section class="elementor-section elementor-top-section elementor-element elementor-element-89a4cbb elementor-section-boxed elementor-section-height-default" data-id="89a4cbb" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-dccb0e1" data-id="dccb0e1" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-3f4332d elementor-widget elementor-widget-heading" data-id="3f4332d" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Authors</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-f7056c2 elementor-widget elementor-widget-mdp-crumber-elementor" data-id="f7056c2" data-element_type="widget" data-e-type="widget" data-widget_type="mdp-crumber-elementor.default">
				<div class="elementor-widget-container">
					        <!-- Start Crumber for Elementor WordPress Plugin -->
		            <div class="mdp-crumber-elementor-box">
                <div class="mdp-crumber-elementor-breadcrumbs">
					        <div class="mdp-crumber-elementor-breadcrumbs-item  mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Home</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				        <div class="mdp-crumber-elementor-breadcrumbs-item mdp-crumber-elementor-breadcrumbs-item-active mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Authors</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				                </div>
            </div>
		        <!-- End Crumber for Elementor WordPress Plugin -->
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-122b1ba elementor-hidden-desktop elementor-section-boxed elementor-section-height-default" data-id="122b1ba" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-8bf8869" data-id="8bf8869" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2c52821 elementor-widget elementor-widget-heading" data-id="2c52821" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h5 class="elementor-heading-title elementor-size-default">Filters</h5>				</div>
				</div>
				<div class="elementor-element elementor-element-450dd2b elementor-nav-menu__align-start elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu" data-id="450dd2b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;&quot;},&quot;layout&quot;:&quot;horizontal&quot;}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-horizontal e--pointer-text e--animation-none">
				<ul id="menu-1-450dd2b" class="elementor-nav-menu" data-smartmenus-id="177944784150565"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5167"><a href="/authors#" class="elementor-item elementor-item-anchor">Shop</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5166"><a href="/authors#" class="elementor-item elementor-item-anchor">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5168"><a href="/authors#" class="elementor-item elementor-item-anchor">Help center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5169"><a href="/authors#" class="elementor-item elementor-item-anchor">Blog</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5170"><a href="/authors#" class="elementor-item elementor-item-anchor">Contacts</a></li>
</ul>			</nav>
						<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true" style="--menu-height: 0;">
				<ul id="menu-2-450dd2b" class="elementor-nav-menu" data-smartmenus-id="17794478415051436"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5167"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Shop</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5166"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5168"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Help center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5169"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Blog</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5170"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Contacts</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-a464f1f elementor-section-boxed elementor-section-height-default" data-id="a464f1f" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-2f20353" data-id="2f20353" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-82cd3da elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="82cd3da" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-fa84781" data-id="fa84781" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-49008fa elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="49008fa" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img fetchpriority="high" decoding="async" width="300" height="300" src="/images/authors/simon-lee-Ue97JK9S0QE-unsplash-2-1-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-3915" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-4654090" data-id="4654090" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-d1cc0fb elementor-widget elementor-widget-heading" data-id="d1cc0fb" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Lydia Davidson</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-39dcafd elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="39dcafd" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-5fc49f3 elementor-widget elementor-widget-text-editor" data-id="5fc49f3" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla								</div>
				</div>
				<div class="elementor-element elementor-element-a17835d elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="a17835d" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-c6b7f25 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="c6b7f25" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-b53abde" data-id="b53abde" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-cbe1037 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="cbe1037" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/mitchell-luo-dKe5P0ZpteA-unsplash-e1654762224184-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2442" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-5805fc4" data-id="5805fc4" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-4fbef7b elementor-widget elementor-widget-heading" data-id="4fbef7b" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Janet Arnold</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-6e792cf elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="6e792cf" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-8a87af5 elementor-widget elementor-widget-text-editor" data-id="8a87af5" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Aliquam vestibulum morbi blandit cursus risus. Mi ipsum faucibus vitae aliquet.								</div>
				</div>
				<div class="elementor-element elementor-element-e0dcf20 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="e0dcf20" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-801b213 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="801b213" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-9adaee4" data-id="9adaee4" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e1bef9f elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="e1bef9f" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/kevin-chin-HvdRVnyV0PQ-unsplash-1-1-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2439" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-d2f7e35" data-id="d2f7e35" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-72b7808 elementor-widget elementor-widget-heading" data-id="72b7808" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Robert Parsons</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-bdf3b23 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="bdf3b23" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-ff12ec6 elementor-widget elementor-widget-text-editor" data-id="ff12ec6" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Egestas sed tempus urna et pharetra pharetra massa pellentesque								</div>
				</div>
				<div class="elementor-element elementor-element-d9af5f3 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="d9af5f3" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-999492a elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="999492a" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-6444636" data-id="6444636" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-c29e25e elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="c29e25e" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/mo-DP0LMBAIzZQ-unsplash-1-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2441" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-616d838" data-id="616d838" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-3b04cb3 elementor-widget elementor-widget-heading" data-id="3b04cb3" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Diane Brown</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-c156373 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="c156373" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-d786ee5 elementor-widget elementor-widget-text-editor" data-id="d786ee5" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Feugiat sed lectus vestibulum mattis ullamcorper. Sed semper risus hendrerit gravida.								</div>
				</div>
				<div class="elementor-element elementor-element-1b4ebe1 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="1b4ebe1" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-a7f32b2 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="a7f32b2" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-1b2f38d" data-id="1b2f38d" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0d54676 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="0d54676" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/milad-fakurian-PjG_SXDkpwQ-unsplash-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2427" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-6d097cf" data-id="6d097cf" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-3b706eb elementor-widget elementor-widget-heading" data-id="3b706eb" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Steve Harrison</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-e82e057 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="e82e057" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-d8b4ec1 elementor-widget elementor-widget-text-editor" data-id="d8b4ec1" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Vitae suscipit tellus mauris a diam maecenas sed enim								</div>
				</div>
				<div class="elementor-element elementor-element-5f0fbad elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="5f0fbad" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-53bc8ee elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="53bc8ee" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-5f4df25" data-id="5f4df25" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-1dc8142 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="1dc8142" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/simon-lee-2XngRU_RNqo-unsplash-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2435" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-c611270" data-id="c611270" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-780a094 elementor-widget elementor-widget-heading" data-id="780a094" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Chris Howard</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-e17c10b elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="e17c10b" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-45387fb elementor-widget elementor-widget-text-editor" data-id="45387fb" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Sed augue lacus viverra vitae congue eu consequat								</div>
				</div>
				<div class="elementor-element elementor-element-f5b3b4a elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="f5b3b4a" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-cc37a08 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="cc37a08" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-a3b8245" data-id="a3b8245" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-5641287 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="5641287" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/mo-NKhckz9B78c-unsplash-1-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2455" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-0645ffe" data-id="0645ffe" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-b5a877c elementor-widget elementor-widget-heading" data-id="b5a877c" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Mildred Flores</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-7d66639 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="7d66639" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-38848de elementor-widget elementor-widget-text-editor" data-id="38848de" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Faucibus ornare suspendisse sed nisi lacus sed viverra tellus 								</div>
				</div>
				<div class="elementor-element elementor-element-5031322 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="5031322" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-9fdace8 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="9fdace8" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-3776c1e" data-id="3776c1e" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0303195 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="0303195" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/simon-lee-zA66MV4EyXc-unsplash-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-5578" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-7203608" data-id="7203608" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0c285cf elementor-widget elementor-widget-heading" data-id="0c285cf" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Stephen Morris</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-de04ef4 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="de04ef4" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-d93f101 elementor-widget elementor-widget-text-editor" data-id="d93f101" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Eget magna fermentum iaculis eu non diam phasellus vestibulum 								</div>
				</div>
				<div class="elementor-element elementor-element-9755072 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="9755072" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-d9b8c0a elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="d9b8c0a" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-d1d82f4" data-id="d1d82f4" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-804a775 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="804a775" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/hans-eiskonen-8Pm_A-OHJGg-unsplash-1-1-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2014" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-77603b6" data-id="77603b6" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-8f7bbaf elementor-widget elementor-widget-heading" data-id="8f7bbaf" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Melinda Chapman</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-f2cb341 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="f2cb341" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-73ebd21 elementor-widget elementor-widget-text-editor" data-id="73ebd21" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Posuere urna nec tincidunt praesent semper feugiat nibh sed								</div>
				</div>
				<div class="elementor-element elementor-element-8e55961 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="8e55961" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-383e01f elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="383e01f" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-1641e7b" data-id="1641e7b" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-f7ca21b elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="f7ca21b" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="300" height="300" src="/images/authors/vadim-bogulov-rP_pS1VMd7c-unsplash-1-300x300.jpg" class="elementor-animation-shrink attachment-medium size-medium wp-image-2431" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-f4decc2" data-id="f4decc2" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-0ef2541 elementor-widget elementor-widget-heading" data-id="0ef2541" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h6 class="elementor-heading-title elementor-size-default">Kathleen Powell</h6>				</div>
				</div>
				<div class="elementor-element elementor-element-ce22e46 elementor-icon-list--layout-inline elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list" data-id="ce22e46" data-element_type="widget" data-e-type="widget" data-widget_type="icon-list.default">
				<div class="elementor-widget-container">
							<ul class="elementor-icon-list-items elementor-inline-items">
							<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-clock"></i>						</span>
										<span class="elementor-icon-list-text">June 22, 2022</span>
									</li>
								<li class="elementor-icon-list-item elementor-inline-item">
											<span class="elementor-icon-list-icon">
							<i aria-hidden="true" class="fas fa-tags"></i>						</span>
										<span class="elementor-icon-list-text">Abctract</span>
									</li>
						</ul>
						</div>
				</div>
				<div class="elementor-element elementor-element-288e3fd elementor-widget elementor-widget-text-editor" data-id="288e3fd" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Bibendum at varius vel pharetra vel turpis. Sagittis orci a scelerisque purus.								</div>
				</div>
				<div class="elementor-element elementor-element-a914b89 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="a914b89" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/authors#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View profile</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
				<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-c1b31d2 elementor-hidden-tablet elementor-hidden-mobile" data-id="c1b31d2" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-d2810f9 elementor-widget elementor-widget-heading" data-id="d2810f9" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h5 class="elementor-heading-title elementor-size-default">Quick links</h5>				</div>
				</div>
				<div class="elementor-element elementor-element-afe3ae8 elementor-nav-menu__align-start elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu" data-id="afe3ae8" data-element_type="widget" data-e-type="widget" data-settings="{&quot;layout&quot;:&quot;vertical&quot;,&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;&lt;i class=\\&quot;\\&quot; aria-hidden=\\&quot;true\\&quot;&gt;&lt;\\/i&gt;&quot;,&quot;library&quot;:&quot;&quot;}}" data-widget_type="nav-menu.default">
				<div class="elementor-widget-container">
								<nav aria-label="Menu" class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-vertical e--pointer-background e--animation-fade">
				<ul id="menu-1-afe3ae8" class="elementor-nav-menu sm-vertical" data-smartmenus-id="17794478415066768"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5167"><a href="/authors#" class="elementor-item elementor-item-anchor">Shop</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5166"><a href="/authors#" class="elementor-item elementor-item-anchor">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5168"><a href="/authors#" class="elementor-item elementor-item-anchor">Help center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5169"><a href="/authors#" class="elementor-item elementor-item-anchor">Blog</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5170"><a href="/authors#" class="elementor-item elementor-item-anchor">Contacts</a></li>
</ul>			</nav>
						<nav class="elementor-nav-menu--dropdown elementor-nav-menu__container" aria-hidden="true" style="--menu-height: 0;">
				<ul id="menu-2-afe3ae8" class="elementor-nav-menu sm-vertical" data-smartmenus-id="1779447841506782"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5167"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Shop</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5166"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5168"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Help center</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5169"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Blog</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5170"><a href="/authors#" class="elementor-item elementor-item-anchor" tabindex="-1">Contacts</a></li>
</ul>			</nav>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				</div>
		
		
			</div>

	
</main>

			`;
