// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `
		
<main id="content" class="site-main post-415 envato_tk_templates type-envato_tk_templates status-publish has-post-thumbnail hentry">

	
	<div class="page-content">
				<div data-elementor-type="wp-post" data-elementor-id="415" class="elementor elementor-415" data-elementor-post-type="envato_tk_templates">
						<section class="elementor-section elementor-top-section elementor-element elementor-element-e641378 elementor-section-boxed elementor-section-height-default" data-id="e641378" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-676a1fc" data-id="676a1fc" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-b2b0d06 elementor-widget elementor-widget-heading" data-id="b2b0d06" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Login</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-8e1858b elementor-widget elementor-widget-mdp-crumber-elementor" data-id="8e1858b" data-element_type="widget" data-e-type="widget" data-widget_type="mdp-crumber-elementor.default">
				<div class="elementor-widget-container">
					        <!-- Start Crumber for Elementor WordPress Plugin -->
		            <div class="mdp-crumber-elementor-box">
                <div class="mdp-crumber-elementor-breadcrumbs">
					        <div class="mdp-crumber-elementor-breadcrumbs-item  mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Home</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				        <div class="mdp-crumber-elementor-breadcrumbs-item mdp-crumber-elementor-breadcrumbs-item-active mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Login</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				                </div>
            </div>
		        <!-- End Crumber for Elementor WordPress Plugin -->
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-f83b577 elementor-section-boxed elementor-section-height-default" data-id="f83b577" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-1a142eb" data-id="1a142eb" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-80457d6 elementor-section-boxed elementor-section-height-default" data-id="80457d6" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-922e1d4" data-id="922e1d4" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-956621c elementor-widget elementor-widget-heading" data-id="956621c" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Login to your account</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-41ef08d elementor-widget elementor-widget-login" data-id="41ef08d" data-element_type="widget" data-e-type="widget" data-widget_type="login.default">
				<div class="elementor-widget-container">
							<form class="elementor-login elementor-form" method="post" action="#" aria-label="Login form">
			<input type="hidden" name="redirect_to" value="/template-kit/user-login/">
			<div class="elementor-form-fields-wrapper">
				<div class="elementor-field-type-text elementor-field-group elementor-column elementor-col-100 elementor-field-required">
					<label for="user-41ef08d" class="elementor-field-label elementor-screen-only"></label>
					<input size="1" type="text" name="log" id="user-41ef08d" placeholder="Username or email address" class="elementor-field elementor-field-textual elementor-size-sm">
				</div>
				<div class="elementor-field-type-text elementor-field-group elementor-column elementor-col-100 elementor-field-required">
					<label for="password-41ef08d" class="elementor-field-label elementor-screen-only"></label>
					<input size="1" type="password" name="pwd" id="password-41ef08d" placeholder="Password" class="elementor-field elementor-field-textual elementor-size-sm">
				</div>

									<div class="elementor-field-type-checkbox elementor-field-group elementor-column elementor-col-100 elementor-remember-me">
						<label for="elementor-login-remember-me">
							<input type="checkbox" id="elementor-login-remember-me" name="rememberme" value="forever">
							Remember Me						</label>
					</div>
				
				<div class="elementor-field-group elementor-column elementor-field-type-submit elementor-col-100">
					<button type="submit" class="elementor-size-sm elementor-button" name="wp-submit">
															<span class="elementor-button-text">Login</span>
												</button>
				</div>

									<div class="elementor-field-group elementor-column elementor-col-100">
																				<a class="elementor-lost-password" href="/login">
								Lost your password?							</a>
						
											</div>
							</div>
		</form>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-36129d0" data-id="36129d0" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e9c9473 elementor-widget__width-auto elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-image animated fadeIn" data-id="e9c9473" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeIn&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img fetchpriority="high" decoding="async" src="/images/login/ferhat-deniz-fors-saE7xiecGkM-unsplash-2-1-1-pq0sitz7ykek5f8l1qidsucicj9y1kamkqg8b1ll4o.jpg" title="ferhat-deniz-fors-saE7xiecGkM-unsplash (2) (1) 1" alt="ferhat-deniz-fors-saE7xiecGkM-unsplash (2) (1) 1" loading="lazy">															</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				</div>
		
		
			</div>

	
</main>

			`;
