// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `
				<div data-elementor-type="archive" data-elementor-id="1186" class="elementor elementor-1186 elementor-location-archive" data-elementor-post-type="elementor_library">
					<section class="elementor-section elementor-top-section elementor-element elementor-element-efae58b elementor-section-full_width elementor-section-content-middle elementor-section-height-default" data-id="efae58b" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
							<div class="elementor-background-overlay"></div>
							<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-2ccbf4e elementor-hidden-tablet elementor-hidden-mobile" data-id="2ccbf4e" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-f41ea06 elementor-widget elementor-widget-spacer" data-id="f41ea06" data-element_type="widget" data-e-type="widget" data-widget_type="spacer.default">
				<div class="elementor-widget-container">
							<div class="elementor-spacer">
			<div class="elementor-spacer-inner"></div>
		</div>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-525f3f1" data-id="525f3f1" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-1e7d82d elementor-widget elementor-widget-theme-archive-title elementor-page-title elementor-widget-heading" data-id="1e7d82d" data-element_type="widget" data-e-type="widget" data-widget_type="theme-archive-title.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Category: Token</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-63fd672 elementor-widget elementor-widget-mdp-crumber-elementor" data-id="63fd672" data-element_type="widget" data-e-type="widget" data-widget_type="mdp-crumber-elementor.default">
				<div class="elementor-widget-container">
					        <!-- Start Crumber for Elementor WordPress Plugin -->
		            <div class="mdp-crumber-elementor-box">
                <div class="mdp-crumber-elementor-breadcrumbs">
					        <div class="mdp-crumber-elementor-breadcrumbs-item  mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Home</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				        <div class="mdp-crumber-elementor-breadcrumbs-item mdp-crumber-elementor-breadcrumbs-item-active mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Blog</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				                </div>
            </div>
		        <!-- End Crumber for Elementor WordPress Plugin -->
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-f861c07 elementor-hidden-tablet elementor-hidden-mobile" data-id="f861c07" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-8e399c2 elementor-widget elementor-widget-spacer" data-id="8e399c2" data-element_type="widget" data-e-type="widget" data-widget_type="spacer.default">
				<div class="elementor-widget-container">
							<div class="elementor-spacer">
			<div class="elementor-spacer-inner"></div>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-0e34b5b elementor-section-boxed elementor-section-height-default" data-id="0e34b5b" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-64139e7" data-id="64139e7" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-fc3aa87 elementor-grid-3 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-archive-posts" data-id="fc3aa87" data-element_type="widget" data-e-type="widget" data-settings="{&quot;archive_classic_row_gap&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:40,&quot;sizes&quot;:[]},&quot;archive_classic_row_gap_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:30,&quot;sizes&quot;:[]},&quot;archive_classic_row_gap_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:30,&quot;sizes&quot;:[]},&quot;archive_classic_columns&quot;:&quot;3&quot;,&quot;archive_classic_columns_tablet&quot;:&quot;2&quot;,&quot;archive_classic_columns_mobile&quot;:&quot;1&quot;,&quot;pagination_type&quot;:&quot;numbers&quot;}" data-widget_type="archive-posts.archive_classic">
				<div class="elementor-widget-container">
							<div class="elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio" role="list">
				<article class="elementor-post elementor-grid-item post-70 post type-post status-publish format-standard has-post-thumbnail hentry category-nft category-token category-uncategorized tag-blockchain tag-internet tag-nft" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail"><img fetchpriority="high" width="768" height="1024" src="/images/blog-2/simon-lee-ldg40aCeOXo-unsplash-1-2-768x1024.jpg" class="attachment-medium_large size-medium_large wp-image-1035" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				Top 10 NFT projects that shocked the Internet with their uniqueness			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 15, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-68 post type-post status-publish format-standard has-post-thumbnail hentry category-nft category-token category-uncategorized tag-3d tag-art tag-cryptocurrency" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="545" src="/images/blog-2/tezos-Yu-HIuvap1s-unsplash-1-1-768x545.jpg" class="attachment-medium_large size-medium_large wp-image-1105" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				NFT art exists in the digital world collector			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 15, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-66 post type-post status-publish format-standard has-post-thumbnail hentry category-nft category-token category-uncategorized tag-bitcoin tag-development tag-images tag-music" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="512" src="/images/blog-2/colored-blocks-on-a-blue-background-2022-04-07-00-38-16-utc-1-1-1-768x512.jpg" class="attachment-medium_large size-medium_large wp-image-1102" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				How will you make best NFT store effectively			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 15, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-59 post type-post status-publish format-standard has-post-thumbnail hentry category-nft category-token category-uncategorized tag-development tag-finance tag-internet" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="512" src="/images/blog-2/tezos-NN8ioR6Y88A-unsplash-1-768x512.jpg" class="attachment-medium_large size-medium_large wp-image-1104" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				Crypto expert responds to a viral takedown on NFT			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 14, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-72 post type-post status-publish format-standard has-post-thumbnail hentry category-nft category-token category-uncategorized tag-blockchain tag-finance tag-internet tag-trends" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="512" src="/images/blog-2/tezos-gWjlDDJdmlI-unsplash-1-1-768x512.jpg" class="attachment-medium_large size-medium_large wp-image-1127" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				Take back ownership of your data and identity with NFT domains			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 14, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-25 post type-post status-publish format-standard has-post-thumbnail hentry category-nft category-token category-uncategorized tag-blockchain tag-development tag-finance" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="768" src="/images/blog-2/kevin-chin-HvdRVnyV0PQ-unsplash-1-1-768x768.jpg" class="attachment-medium_large size-medium_large wp-image-2439" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				Important updates for listing and delisting your NFTs			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 14, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-24 post type-post status-publish format-standard has-post-thumbnail hentry category-token category-uncategorized tag-development tag-games tag-nft" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="390" src="/images/blog-2/niklas-liniger-fIPXnxN7-9A-unsplash-1-e1652950002551-768x390.jpg" class="attachment-medium_large size-medium_large wp-image-1129" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				Bringing virtual games into the real world			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 14, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-36 post type-post status-publish format-standard has-post-thumbnail hentry category-token category-uncategorized tag-art tag-games tag-images tag-music" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="576" src="/images/blog-2/ferhat-deniz-fors-e1qoosfnAvA-unsplash-1-768x576.jpg" class="attachment-medium_large size-medium_large wp-image-1151" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				Welcome to Xchain			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 13, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				<article class="elementor-post elementor-grid-item post-39 post type-post status-publish format-standard has-post-thumbnail hentry category-token category-uncategorized tag-bitcoin tag-blockchain tag-etherium" role="listitem">
				<a class="elementor-post__thumbnail__link" href="/blog" tabindex="-1">
			<div class="elementor-post__thumbnail elementor-fit-height"><img loading="lazy" width="768" height="584" src="/images/blog-2/milad-fakurian-E8Ufcyxz514-unsplash-1-1-768x584.jpg" class="attachment-medium_large size-medium_large wp-image-1168" alt=""></div>
		</a>
				<div class="elementor-post__text">
				<h3 class="elementor-post__title">
			<a href="/blog">
				How to programmatically bid on english auctions on Xchain			</a>
		</h3>
				<div class="elementor-post__meta-data">
					<span class="elementor-post-author">
			merkulove		</span>
				<span class="elementor-post-date">
			August 13, 2020		</span>
				<span class="elementor-post-avatar">
			No Comments		</span>
				</div>
				</div>
				</article>
				</div>
		
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				</div>
				`;
