// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `
				<div data-elementor-type="product-archive" data-elementor-id="5542" class="elementor elementor-5542 elementor-location-archive product" data-elementor-post-type="elementor_library">
					<section class="elementor-section elementor-top-section elementor-element elementor-element-c31e52a elementor-section-boxed elementor-section-height-default" data-id="c31e52a" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-74a548b" data-id="74a548b" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-ce4fb8f elementor-widget elementor-widget-theme-archive-title elementor-page-title elementor-widget-heading" data-id="ce4fb8f" data-element_type="widget" data-e-type="widget" data-widget_type="theme-archive-title.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Category: ⚡ Utility</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-97b9c85 elementor-widget elementor-widget-mdp-crumber-elementor" data-id="97b9c85" data-element_type="widget" data-e-type="widget" data-widget_type="mdp-crumber-elementor.default">
				<div class="elementor-widget-container">
					        <!-- Start Crumber for Elementor WordPress Plugin -->
		            <div class="mdp-crumber-elementor-box">
                <div class="mdp-crumber-elementor-breadcrumbs">
					        <div class="mdp-crumber-elementor-breadcrumbs-item  mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Home</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				        <div class="mdp-crumber-elementor-breadcrumbs-item mdp-crumber-elementor-breadcrumbs-item-active mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Shop</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				                </div>
            </div>
		        <!-- End Crumber for Elementor WordPress Plugin -->
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-03b5817 elementor-section-boxed elementor-section-height-default" data-id="03b5817" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-caa85da" data-id="caa85da" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-8903d4e premium-woo-product-align-left premium-qv-hidden-yes elementor-widget elementor-widget-premium-woo-products" data-id="8903d4e" data-element_type="widget" data-e-type="widget" data-widget_type="premium-woo-products.grid-3">
				<div class="elementor-widget-container">
					<div class="premium-woocommerce premium-woo-products-grid premium-woo-skin-grid-3 premium-woo-query-all" data-page-id="5542" data-skin="grid_3" data-quick-view="yes"><div class="premium-woo-products-inner premium-woo-product__hover-zoomin"><ul class="products columns-4">

<li class=" post-2472 product first instock shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/pawel-czerwinski-hNrd99q5peI-unsplash-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="2472"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				📸 Photography			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Abstract image</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>2,560.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_2472" data-quantity="1" class="button product_type_external" data-product_id="2472" data-product_sku="1234598-2" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_2472" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-1660 product  instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/milad-fakurian-PjG_SXDkpwQ-unsplash-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="1660"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				✨ Collectibles			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Сolorful 3D object</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>890.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_1660" data-quantity="1" class="button product_type_external" data-product_id="1660" data-product_sku="123455-1-1-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_1660" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-214 product  instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/anunay-rai-awMWm6ayLTc-unsplash-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="214"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				🔥 Trading cards			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Logical impact</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>1,400.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_214" data-quantity="1" class="button product_type_external" data-product_id="214" data-product_sku="123455-1-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_214" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-212 product last instock shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img fetchpriority="high" src="/images/shop-2/simon-lee-fyZOY0HiF9A-unsplash-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="212"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				🎨 Art			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Infinite figure</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>890.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_212" data-quantity="1" class="button product_type_external" data-product_id="212" data-product_sku="123455" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_212" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-211 product first instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/simon-lee-zA66MV4EyXc-unsplash-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="211"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				🎨 Art			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">The image of a man</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>1,200.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_211" data-quantity="1" class="button product_type_external" data-product_id="211" data-product_sku="1234511" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_211" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-210 product  instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/kevin-chin-HvdRVnyV0PQ-unsplash-1-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="210"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				⚡ Utility			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">3D object Loppi</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>2,560.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_210" data-quantity="1" class="button product_type_external" data-product_id="210" data-product_sku="1234598-1-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_210" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-209 product  instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/mo-DP0LMBAIzZQ-unsplash-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="209"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				ðŸŒ Virtual worlds			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">3D renders</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>2,560.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_209" data-quantity="1" class="button product_type_external" data-product_id="209" data-product_sku="1234598-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_209" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-208 product last instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/simon-lee-Ue97JK9S0QE-unsplash-2-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="208"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				🎨 Art			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Pixel art</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>2,560.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_208" data-quantity="1" class="button product_type_external" data-product_id="208" data-product_sku="1234598" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_208" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-207 product first instock shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/vadim-bogulov-rP_pS1VMd7c-unsplash-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="207"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				🔥 Trading cards			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Pixel art</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>230.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_207" data-quantity="1" class="button product_type_external" data-product_id="207" data-product_sku="12345234-1-1-1-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_207" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-206 product  instock featured shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><div class="premium-woo-ribbon-container">	<div class="premium-woo-product-featured-wrap">
		<span class="premium-woo-product-featured">Hot</span>
	</div>
	</div><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/johan-lindberg-IcWtW5WsmTg-unsplash-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="206"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				🎨 Art			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">3d art figure</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>230.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_206" data-quantity="1" class="button product_type_external" data-product_id="206" data-product_sku="12345234-1-1-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_206" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-205 product  instock shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/davisuko-rhUU1pemhQ0-unsplash-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="205"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				📸 Photography			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">Abstract image</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>230.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_205" data-quantity="1" class="button product_type_external" data-product_id="205" data-product_sku="12345234-1-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_205" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>

<li class=" post-204 product last instock shipping-taxable product-type-external">
	<div class="premium-woo-product-wrapper premium-con-lq__none">
		<div class="premium-woo-product-thumbnail"><a href="/product" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="/images/shop-2/hans-eiskonen-8Pm_A-OHJGg-unsplash-1-1-600x600.jpg" alt=""></a><div class="premium-woo-qv-data" data-product-id="204"></div></div><div class="premium-woo-products-details-wrap">			<span class="premium-woo-product-category">
				ðŸŒ Virtual worlds			</span>
			<a href="/product" class="premium-woo-product__link"><h2 class="woocommerce-loop-product__title">3d art figure</h2></a>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">$</span>230.00</bdi></span></span>
<div class="premium-woo-product-actions-wrapper"><div class="premium-woo-atc-button" data-variations="&quot;true&quot;"><a href="/shop-2" aria-describedby="woocommerce_loop_add_to_cart_link_describedby_204" data-quantity="1" class="button product_type_external" data-product_id="204" data-product_sku="12345234-1" aria-label="Buy now" rel="nofollow">Buy now</a>	<span id="woocommerce_loop_add_to_cart_link_describedby_204" class="screen-reader-text">
			</span>
</div></div></div>	</div>
</li>
</ul>
<nav class="premium-woo-products-pagination">
	<ul class="page-numbers">
	<li><span aria-label="Page 1" aria-current="page" class="page-numbers current">1</span></li>
	<li><a aria-label="Page 2" class="page-numbers" href="/shop">2</a></li>
	<li><a aria-label="Page 3" class="page-numbers" href="/shop">3</a></li>
</ul>
</nav>
</div></div>
				</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				</div>
				`;
