// Auto-generated by scripts/extract-fragments.mjs - do not edit by hand.
export default `
		
<main id="content" class="site-main post-417 envato_tk_templates type-envato_tk_templates status-publish has-post-thumbnail hentry">

	
	<div class="page-content">
				<div data-elementor-type="wp-post" data-elementor-id="417" class="elementor elementor-417" data-elementor-post-type="envato_tk_templates">
						<section class="elementor-section elementor-top-section elementor-element elementor-element-282f482 elementor-section-full_width elementor-section-content-middle elementor-section-height-default" data-id="282f482" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
							<div class="elementor-background-overlay"></div>
							<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-5a41120 elementor-hidden-tablet elementor-hidden-mobile" data-id="5a41120" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-7f80401 elementor-widget elementor-widget-spacer" data-id="7f80401" data-element_type="widget" data-e-type="widget" data-widget_type="spacer.default">
				<div class="elementor-widget-container">
							<div class="elementor-spacer">
			<div class="elementor-spacer-inner"></div>
		</div>
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-015b364" data-id="015b364" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-bdb1f58 elementor-widget elementor-widget-heading" data-id="bdb1f58" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">About Us</h2>				</div>
				</div>
				<div class="elementor-element elementor-element-99470c4 elementor-widget elementor-widget-mdp-crumber-elementor" data-id="99470c4" data-element_type="widget" data-e-type="widget" data-widget_type="mdp-crumber-elementor.default">
				<div class="elementor-widget-container">
					        <!-- Start Crumber for Elementor WordPress Plugin -->
		            <div class="mdp-crumber-elementor-box">
                <div class="mdp-crumber-elementor-breadcrumbs">
					        <div class="mdp-crumber-elementor-breadcrumbs-item  mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>Home</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				        <div class="mdp-crumber-elementor-breadcrumbs-item mdp-crumber-elementor-breadcrumbs-item-active mdp-crumber-elementor-breadcrumbs-icon-position-">
												                    <span>About</span>
							        </div>
		            <span class="mdp-crumber-elementor-separator mdp-crumber-elementor-separator-hide-last">
            •        </span>
				                </div>
            </div>
		        <!-- End Crumber for Elementor WordPress Plugin -->
						</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-8ef7835 elementor-hidden-tablet elementor-hidden-mobile" data-id="8ef7835" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-4977f4b elementor-widget elementor-widget-spacer" data-id="4977f4b" data-element_type="widget" data-e-type="widget" data-widget_type="spacer.default">
				<div class="elementor-widget-container">
							<div class="elementor-spacer">
			<div class="elementor-spacer-inner"></div>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-0bc2c7d elementor-section-content-bottom elementor-section-boxed elementor-section-height-default" data-id="0bc2c7d" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-4284c6e" data-id="4284c6e" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-62d6990 elementor-widget elementor-widget-image" data-id="62d6990" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img fetchpriority="high" decoding="async" width="800" height="800" src="/images/about/ferhat-deniz-fors-e1qoosfnAvA-unsplash-1024x1024.jpg" class="attachment-large size-large wp-image-4225" alt="" sizes="(max-width: 800px) 100vw, 800px">															</div>
				</div>
				<div class="elementor-element elementor-element-ec7af39 elementor-widget__width-initial elementor-widget-tablet__width-initial elementor-widget-mobile__width-initial elementor-absolute elementor-hidden-mobile elementor-hidden-tablet elementor-widget elementor-widget-image elementor-motion-effects-parent" data-id="ec7af39" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;motion_fx_motion_fx_mouse&quot;:&quot;yes&quot;,&quot;motion_fx_mouseTrack_effect&quot;:&quot;yes&quot;,&quot;motion_fx_mouseTrack_direction&quot;:&quot;negative&quot;,&quot;motion_fx_mouseTrack_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:0.200000000000000011102230246251565404236316680908203125,&quot;sizes&quot;:[]}}" data-widget_type="image.default">
				<div class="elementor-widget-container elementor-motion-effects-element" style="transform: translateX(var(--translateX))translateY(var(--translateY)); --translateX: 0.53125px; --translateY: 1.9056261343012708px;">
															<img loading="lazy" decoding="async" width="400" height="274" src="/images/about/element-2-e1655113849501.png" class="attachment-full size-full wp-image-5507" alt="" sizes="(max-width: 400px) 100vw, 400px">															</div>
				</div>
				<div class="elementor-element elementor-element-7515ccd elementor-widget__width-initial elementor-widget-tablet__width-initial elementor-widget-mobile__width-initial elementor-absolute elementor-hidden-mobile elementor-hidden-tablet elementor-widget elementor-widget-image elementor-motion-effects-parent" data-id="7515ccd" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;motion_fx_motion_fx_mouse&quot;:&quot;yes&quot;,&quot;motion_fx_mouseTrack_effect&quot;:&quot;yes&quot;,&quot;motion_fx_mouseTrack_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:0.200000000000000011102230246251565404236316680908203125,&quot;sizes&quot;:[]}}" data-widget_type="image.default">
				<div class="elementor-widget-container elementor-motion-effects-element" style="transform: translateX(var(--translateX))translateY(var(--translateY)); --translateX: -0.53125px; --translateY: -1.9056261343012708px;">
															<img loading="lazy" decoding="async" width="400" height="143" src="/images/about/element-3-e1655113712872.png" class="attachment-full size-full wp-image-5508" alt="" sizes="(max-width: 400px) 100vw, 400px">															</div>
				</div>
				<div class="elementor-element elementor-element-3de6102 elementor-widget__width-initial elementor-widget-tablet__width-initial elementor-widget-mobile__width-initial elementor-absolute elementor-hidden-mobile elementor-hidden-tablet elementor-widget elementor-widget-image elementor-motion-effects-parent" data-id="3de6102" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;motion_fx_motion_fx_mouse&quot;:&quot;yes&quot;,&quot;motion_fx_mouseTrack_effect&quot;:&quot;yes&quot;,&quot;motion_fx_mouseTrack_direction&quot;:&quot;negative&quot;,&quot;motion_fx_mouseTrack_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:0.200000000000000011102230246251565404236316680908203125,&quot;sizes&quot;:[]}}" data-widget_type="image.default">
				<div class="elementor-widget-container elementor-motion-effects-element" style="transform: translateX(var(--translateX))translateY(var(--translateY)); --translateX: 0.53125px; --translateY: 1.9056261343012708px;">
															<img loading="lazy" decoding="async" width="400" height="237" src="/images/about/element-4-e1655113726369.png" class="attachment-full size-full wp-image-5509" alt="" sizes="(max-width: 400px) 100vw, 400px">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-4b18f60" data-id="4b18f60" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-37ac0c2 elementor-section-boxed elementor-section-height-default" data-id="37ac0c2" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-50f4123 elementor-hidden-tablet elementor-hidden-mobile" data-id="50f4123" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2ceeed1 elementor-widget__width-auto elementor-widget elementor-widget-image elementor-motion-effects-parent" data-id="2ceeed1" data-element_type="widget" data-e-type="widget" data-settings="{&quot;motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_effect&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:1,&quot;sizes&quot;:[]},&quot;motion_fx_translateY_affectedRange&quot;:{&quot;unit&quot;:&quot;%&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;start&quot;:0,&quot;end&quot;:100}},&quot;motion_fx_devices&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}" data-widget_type="image.default">
				<div class="elementor-widget-container elementor-motion-effects-element" style="--translateY: 41.59px; --e-transform-transition-duration: 100ms; transform: translateY(var(--translateY));">
															<img loading="lazy" decoding="async" width="300" height="217" src="/images/about/simon-lee-ldg40aCeOXo-unsplash-1-1-300x217.png" class="attachment-medium size-medium wp-image-678" alt="" sizes="(max-width: 300px) 100vw, 300px">															</div>
				</div>
				<div class="elementor-element elementor-element-9c438c2 elementor-widget elementor-widget-spacer" data-id="9c438c2" data-element_type="widget" data-e-type="widget" data-widget_type="spacer.default">
				<div class="elementor-widget-container">
							<div class="elementor-spacer">
			<div class="elementor-spacer-inner"></div>
		</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-inner-section elementor-element elementor-element-d9467e3 elementor-section-boxed elementor-section-height-default" data-id="d9467e3" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-c5c0188" data-id="c5c0188" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-145ef3a elementor-widget elementor-widget-heading" data-id="145ef3a" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Who we are?</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-a7dcbb6 elementor-widget elementor-widget-text-editor" data-id="a7dcbb6" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-98b7ab9 elementor-section-full_width elementor-section-height-default" data-id="98b7ab9" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-a1a74fe" data-id="a1a74fe" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-43d708f elementor-widget elementor-widget-mdp-crawler-elementor" data-id="43d708f" data-element_type="widget" data-e-type="widget" data-widget_type="mdp-crawler-elementor.default">
				<div class="elementor-widget-container">
					        <!-- Start Crawler for Elementor WordPress Plugin -->
        <div class="mdp-crawler-elementor-box mdp-crawler-elementor-box-0" data-ticker-type="ticker">
            <div class="mdp-crawler-elementor-ticker   mdp-crawler-elementor-ticker-ticker-type  mdp-crawler-elementor-ticker-label-align-">
				                <div class="mdp-crawler-elementor-content-wrapper">
                    <div class="mdp-crawler-elementor-ticker-content mdp-crawler-elementor-ticker-animation-normal ">
																				                            <div class="mdp-crawler-elementor-ticker-item">
                                <a>
									new creative economy                                </a>
                            </div>
																																		                            <div class="mdp-crawler-elementor-ticker-item">
                                <a>
									new creative economy                                </a>
                            </div>
																																		                            <div class="mdp-crawler-elementor-ticker-item">
                                <a>
									new creative economy                                </a>
                            </div>
																																		                            <div class="mdp-crawler-elementor-ticker-item">
                                <a>
									new creative economy                                </a>
                            </div>
																																		                            <div class="mdp-crawler-elementor-ticker-item">
                                <a>
									new creative economy                                </a>
                            </div>
																																		                            <div class="mdp-crawler-elementor-ticker-item">
                                <a>
									new creative economy                                </a>
                            </div>
																				                    </div>
                </div>
				            </div>
        </div>
        <!-- End Crawler for Elementor WordPress Plugin -->
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-1678d40 elementor-section-boxed elementor-section-height-default" data-id="1678d40" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-extended">
					<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-bd72cff" data-id="bd72cff" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-c7e554d elementor-position-top elementor-widget elementor-widget-image-box" data-id="c7e554d" data-element_type="widget" data-e-type="widget" data-widget_type="image-box.default">
				<div class="elementor-widget-container">
					<div class="elementor-image-box-wrapper"><figure class="elementor-image-box-img"><img loading="lazy" decoding="async" width="60" height="60" src="/images/about/shield-check.png" class="elementor-animation-shrink attachment-full size-full wp-image-784" alt=""></figure><div class="elementor-image-box-content"><h3 class="elementor-image-box-title">High security <br> assets transfer</h3></div></div>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-6e70562" data-id="6e70562" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-813dbe5 elementor-position-top elementor-widget elementor-widget-image-box" data-id="813dbe5" data-element_type="widget" data-e-type="widget" data-widget_type="image-box.default">
				<div class="elementor-widget-container">
					<div class="elementor-image-box-wrapper"><figure class="elementor-image-box-img"><img loading="lazy" decoding="async" width="60" height="60" src="/images/about/support.png" class="elementor-animation-shrink attachment-full size-full wp-image-785" alt=""></figure><div class="elementor-image-box-content"><h3 class="elementor-image-box-title">24/7 live support <br> with skype &amp; email</h3></div></div>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-36b50fb" data-id="36b50fb" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-28d3393 elementor-position-top elementor-widget elementor-widget-image-box" data-id="28d3393" data-element_type="widget" data-e-type="widget" data-widget_type="image-box.default">
				<div class="elementor-widget-container">
					<div class="elementor-image-box-wrapper"><figure class="elementor-image-box-img"><img loading="lazy" decoding="async" width="60" height="60" src="/images/about/trophy-star.png" class="elementor-animation-shrink attachment-full size-full wp-image-786" alt=""></figure><div class="elementor-image-box-content"><h3 class="elementor-image-box-title">Top class &amp; NFT <br> products</h3></div></div>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-767830d" data-id="767830d" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-e8f8136 elementor-position-top elementor-widget elementor-widget-image-box" data-id="e8f8136" data-element_type="widget" data-e-type="widget" data-widget_type="image-box.default">
				<div class="elementor-widget-container">
					<div class="elementor-image-box-wrapper"><figure class="elementor-image-box-img"><img loading="lazy" decoding="async" width="60" height="60" src="/images/about/rocket-launch.png" class="elementor-animation-shrink attachment-full size-full wp-image-783" alt=""></figure><div class="elementor-image-box-content"><h3 class="elementor-image-box-title">Regular training <br> &amp; seller courses</h3></div></div>				</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-ec63f5b elementor-section-boxed elementor-section-height-default" data-id="ec63f5b" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-36a8e83" data-id="36a8e83" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-ee93c07 elementor-widget elementor-widget-image animated zoomIn" data-id="ee93c07" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;zoomIn&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
																<a href="/about#elementor-action%3Aaction%3Dlightbox%26settings%3DeyJ0eXBlIjoidmlkZW8iLCJ2aWRlb1R5cGUiOiJ5b3V0dWJlIiwidXJsIjoiaHR0cHM6XC9cL3d3dy55b3V0dWJlLmNvbVwvZW1iZWRcL1hIT21CVjRqc19FP2ZlYXR1cmU9b2VtYmVkIn0%3D">
							<img loading="lazy" decoding="async" width="110" height="110" src="/images/about/play.png" class="elementor-animation-push attachment-medium size-medium wp-image-816" alt="" sizes="(max-width: 110px) 100vw, 110px">								</a>
															</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-c9d4be4 elementor-section-boxed elementor-section-height-default" data-id="c9d4be4" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-8fed450 elementor-motion-effects-parent animated fadeInUp" data-id="8fed450" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_effect&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:0.5,&quot;sizes&quot;:[]},&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false,&quot;motion_fx_translateY_affectedRange&quot;:{&quot;unit&quot;:&quot;%&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;start&quot;:0,&quot;end&quot;:100}},&quot;motion_fx_devices&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}">
			<div class="elementor-widget-wrap elementor-element-populated elementor-motion-effects-element" style="--translateY: 25px; --e-transform-transition-duration: 100ms; transform: translateY(var(--translateY));">
						<div class="elementor-element elementor-element-935819f elementor-widget elementor-widget-heading" data-id="935819f" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Our mission</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-6a793c4 elementor-widget elementor-widget-text-editor" data-id="6a793c4" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 								</div>
				</div>
				<div class="elementor-element elementor-element-4a23d39 elementor-align-left elementor-mobile-align-justify elementor-widget elementor-widget-button animated fadeInUp" data-id="4a23d39" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInUp&quot;}" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/about#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">See our blog</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-1dea0eb elementor-hidden-mobile" data-id="1dea0eb" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-3ce0a85 elementor-widget__width-initial elementor-absolute elementor-widget-tablet__width-initial elementor-widget elementor-widget-image" data-id="3ce0a85" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="1735" height="1010" src="/images/about/element_statistic-e1652868023640.png" class="attachment-full size-full wp-image-841" alt="" sizes="(max-width: 1735px) 100vw, 1735px">															</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-81b06ae elementor-section-full_width elementor-hidden-mobile elementor-section-height-default" data-id="81b06ae" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-6e44363" data-id="6e44363" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-bf32bc8 elementor-widget-tablet__width-initial elementor-hidden-mobile elementor-widget__width-initial elementor-absolute elementor-invisible elementor-widget elementor-widget-image elementor-motion-effects-parent" data-id="bf32bc8" data-element_type="widget" data-e-type="widget" data-settings="{&quot;motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_effect&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_direction&quot;:&quot;negative&quot;,&quot;motion_fx_translateY_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:0.5,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;rotateIn&quot;,&quot;motion_fx_devices&quot;:[&quot;desktop&quot;],&quot;_position&quot;:&quot;absolute&quot;,&quot;motion_fx_translateY_affectedRange&quot;:{&quot;unit&quot;:&quot;%&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;start&quot;:0,&quot;end&quot;:100}}}" data-widget_type="image.default">
				<div class="elementor-widget-container elementor-motion-effects-element" style="--translateY: -25px; --e-transform-transition-duration: 100ms; transform: translateY(var(--translateY));">
															<img loading="lazy" decoding="async" width="450" height="444" src="/images/about/element_about-e1654591202723.png" class="attachment-medium_large size-medium_large wp-image-3644" alt="" sizes="(max-width: 450px) 100vw, 450px">															</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-f83135b elementor-section-boxed elementor-section-height-default" data-id="f83135b" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-154585d" data-id="154585d" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2eca955 elementor-widget elementor-widget-heading" data-id="2eca955" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Xchain statistics</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-02e83be elementor-widget elementor-widget-text-editor" data-id="02e83be" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-93b90d4 elementor-section-boxed elementor-section-height-default elementor-invisible" data-id="93b90d4" data-element_type="section" data-e-type="section" data-settings="{&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-ab6bfb9" data-id="ab6bfb9" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-f20b8b1 elementor-widget elementor-widget-counter" data-id="f20b8b1" data-element_type="widget" data-e-type="widget" data-widget_type="counter.default">
				<div class="elementor-widget-container">
							<div class="elementor-counter">
						<div class="elementor-counter-number-wrapper">
				<span class="elementor-counter-number-prefix"></span>
				<span class="elementor-counter-number" data-duration="2000" data-to-value="250" data-from-value="0" data-delimiter=",">0</span>
				<span class="elementor-counter-number-suffix">K</span>
			</div>
		</div>
						</div>
				</div>
				<div class="elementor-element elementor-element-80ce7d2 elementor-widget elementor-widget-heading" data-id="80ce7d2" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">All NFT's</h2>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-fc0e0f2" data-id="fc0e0f2" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-da8fa2f elementor-widget elementor-widget-counter" data-id="da8fa2f" data-element_type="widget" data-e-type="widget" data-widget_type="counter.default">
				<div class="elementor-widget-container">
							<div class="elementor-counter">
						<div class="elementor-counter-number-wrapper">
				<span class="elementor-counter-number-prefix"></span>
				<span class="elementor-counter-number" data-duration="2000" data-to-value="3.5" data-from-value="0" data-delimiter=",">0</span>
				<span class="elementor-counter-number-suffix">K</span>
			</div>
		</div>
						</div>
				</div>
				<div class="elementor-element elementor-element-05884e4 elementor-widget elementor-widget-heading" data-id="05884e4" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">All creators</h2>				</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-3c7461c elementor-section-boxed elementor-section-height-default elementor-invisible" data-id="3c7461c" data-element_type="section" data-e-type="section" data-settings="{&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-c9febc1" data-id="c9febc1" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-c282066 elementor-widget elementor-widget-counter" data-id="c282066" data-element_type="widget" data-e-type="widget" data-widget_type="counter.default">
				<div class="elementor-widget-container">
							<div class="elementor-counter">
						<div class="elementor-counter-number-wrapper">
				<span class="elementor-counter-number-prefix"></span>
				<span class="elementor-counter-number" data-duration="2000" data-to-value="56" data-from-value="0" data-delimiter=",">0</span>
				<span class="elementor-counter-number-suffix">K</span>
			</div>
		</div>
						</div>
				</div>
				<div class="elementor-element elementor-element-a741b95 elementor-widget elementor-widget-heading" data-id="a741b95" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Сollections</h2>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-34ed22a" data-id="34ed22a" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-7a1b17d elementor-widget elementor-widget-counter" data-id="7a1b17d" data-element_type="widget" data-e-type="widget" data-widget_type="counter.default">
				<div class="elementor-widget-container">
							<div class="elementor-counter">
						<div class="elementor-counter-number-wrapper">
				<span class="elementor-counter-number-prefix"></span>
				<span class="elementor-counter-number" data-duration="2000" data-to-value="490" data-from-value="0" data-delimiter=",">0</span>
				<span class="elementor-counter-number-suffix"></span>
			</div>
		</div>
						</div>
				</div>
				<div class="elementor-element elementor-element-f9201f6 elementor-widget elementor-widget-heading" data-id="f9201f6" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h2 class="elementor-heading-title elementor-size-default">Level one seller</h2>				</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-741d7ac elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="741d7ac" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-61bab0c" data-id="61bab0c" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-cf59615 elementor-widget elementor-widget-heading" data-id="cf59615" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Meet the team⚡</h3>				</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-5ed38ac elementor-hidden-mobile" data-id="5ed38ac" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-f19e466 elementor-align-right elementor-widget elementor-widget-button" data-id="f19e466" data-element_type="widget" data-e-type="widget" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/about#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View all team</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-f7a18ee elementor-section-boxed elementor-section-height-default" data-id="f7a18ee" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-4ef03f5 elementor-invisible" data-id="4ef03f5" data-element_type="column" data-e-type="column" data-settings="{&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-0d3ac4a elementor-section-boxed elementor-section-height-default" data-id="0d3ac4a" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-8aa2f5d" data-id="8aa2f5d" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2a96086 elementor-widget__width-auto elementor-widget elementor-widget-image" data-id="2a96086" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img decoding="async" src="/images/about/aldi-sigun-rTCDPl3C_os-unsplash-1-pqla1easv8lq1avf2dwfzep3lhc712awi6ucys1jd0.jpg" title="aldi-sigun-rTCDPl3C_os-unsplash 1" alt="aldi-sigun-rTCDPl3C_os-unsplash 1" class="elementor-animation-shrink" loading="lazy">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-f65d04e" data-id="f65d04e" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-6dd0831 elementor-widget elementor-widget-heading" data-id="6dd0831" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Robert Atkins</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-f4efeea elementor-widget elementor-widget-heading" data-id="f4efeea" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Developer</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-f52020b elementor-widget elementor-widget-text-editor" data-id="f52020b" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Mattis molestie a iaculis at erat. Ultricies leo integer malesuada nunc vel risus commodo. Nisi est sit amet facilisis.								</div>
				</div>
				<div class="elementor-element elementor-element-3b0bb5c elementor-grid-3 e-grid-align-left e-grid-align-mobile-center elementor-shape-rounded elementor-widget elementor-widget-social-icons" data-id="3b0bb5c" data-element_type="widget" data-e-type="widget" data-widget_type="social-icons.default">
				<div class="elementor-widget-container">
							<div class="elementor-social-icons-wrapper elementor-grid" role="list">
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-twitter elementor-repeater-item-05be2cd" target="_blank">
						<span class="elementor-screen-only">Twitter</span>
						<i aria-hidden="true" class="fab fa-twitter"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-facebook-f elementor-repeater-item-5498b4f" target="_blank">
						<span class="elementor-screen-only">Facebook-f</span>
						<i aria-hidden="true" class="fab fa-facebook-f"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-instagram elementor-repeater-item-418ce82" target="_blank">
						<span class="elementor-screen-only">Instagram</span>
						<i aria-hidden="true" class="fab fa-instagram"></i>					</a>
				</span>
					</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-c25809d elementor-invisible" data-id="c25809d" data-element_type="column" data-e-type="column" data-settings="{&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-86c5776 elementor-section-boxed elementor-section-height-default" data-id="86c5776" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-53f0082" data-id="53f0082" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-9d490a9 elementor-widget__width-auto elementor-widget elementor-widget-image" data-id="9d490a9" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img decoding="async" src="/images/about/aldi-sigun-pmACe385Ruo-unsplash-pqla3buuwz8xwg2ds7yu3x57jztcunz1fr4ah96ekk.jpg" title="aldi-sigun-pmACe385Ruo-unsplash" alt="aldi-sigun-pmACe385Ruo-unsplash" class="elementor-animation-shrink" loading="lazy">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-ed417e4" data-id="ed417e4" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-82235de elementor-widget elementor-widget-heading" data-id="82235de" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Amanda Murphy</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-aba3798 elementor-widget elementor-widget-heading" data-id="aba3798" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Developer</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-4dc182c elementor-widget elementor-widget-text-editor" data-id="4dc182c" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Ligula ullamcorper malesuada proin libero nunc. Scelerisque felis imperdiet proin fermentum. Praesent elementum facilisis leo vel fringilla.								</div>
				</div>
				<div class="elementor-element elementor-element-67cd3f0 elementor-grid-3 e-grid-align-left e-grid-align-mobile-center elementor-shape-rounded elementor-widget elementor-widget-social-icons" data-id="67cd3f0" data-element_type="widget" data-e-type="widget" data-widget_type="social-icons.default">
				<div class="elementor-widget-container">
							<div class="elementor-social-icons-wrapper elementor-grid" role="list">
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-twitter elementor-repeater-item-05be2cd" target="_blank">
						<span class="elementor-screen-only">Twitter</span>
						<i aria-hidden="true" class="fab fa-twitter"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-facebook-f elementor-repeater-item-5498b4f" target="_blank">
						<span class="elementor-screen-only">Facebook-f</span>
						<i aria-hidden="true" class="fab fa-facebook-f"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-instagram elementor-repeater-item-418ce82" target="_blank">
						<span class="elementor-screen-only">Instagram</span>
						<i aria-hidden="true" class="fab fa-instagram"></i>					</a>
				</span>
					</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-9043142 elementor-section-boxed elementor-section-height-default" data-id="9043142" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-1d5538e elementor-invisible" data-id="1d5538e" data-element_type="column" data-e-type="column" data-settings="{&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-5ec5efa elementor-section-boxed elementor-section-height-default" data-id="5ec5efa" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-81e4638" data-id="81e4638" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-2ec8dbe elementor-widget__width-auto elementor-widget elementor-widget-image" data-id="2ec8dbe" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img decoding="async" src="/images/about/aldi-sigun-unt3066GV-E-unsplash-1-pqla26hyk9obplqghq3927kxf1h7fzeum2exd2vq6c.jpg" title="aldi-sigun-unt3066GV-E-unsplash 1" alt="aldi-sigun-unt3066GV-E-unsplash 1" class="elementor-animation-shrink" loading="lazy">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-0503275" data-id="0503275" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-ff7829a elementor-widget elementor-widget-heading" data-id="ff7829a" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Kirk Miller</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-5ec1c14 elementor-widget elementor-widget-heading" data-id="5ec1c14" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">CEO &amp; 3D Designer</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-e97bf89 elementor-widget elementor-widget-text-editor" data-id="e97bf89" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.								</div>
				</div>
				<div class="elementor-element elementor-element-d4c5e0c elementor-grid-3 e-grid-align-left e-grid-align-mobile-center elementor-shape-rounded elementor-widget elementor-widget-social-icons" data-id="d4c5e0c" data-element_type="widget" data-e-type="widget" data-widget_type="social-icons.default">
				<div class="elementor-widget-container">
							<div class="elementor-social-icons-wrapper elementor-grid" role="list">
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-twitter elementor-repeater-item-05be2cd" target="_blank">
						<span class="elementor-screen-only">Twitter</span>
						<i aria-hidden="true" class="fab fa-twitter"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-facebook-f elementor-repeater-item-5498b4f" target="_blank">
						<span class="elementor-screen-only">Facebook-f</span>
						<i aria-hidden="true" class="fab fa-facebook-f"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-instagram elementor-repeater-item-418ce82" target="_blank">
						<span class="elementor-screen-only">Instagram</span>
						<i aria-hidden="true" class="fab fa-instagram"></i>					</a>
				</span>
					</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-e78cd7b elementor-invisible" data-id="e78cd7b" data-element_type="column" data-e-type="column" data-settings="{&quot;animation&quot;:&quot;fadeInUp&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-3a021c1 elementor-section-boxed elementor-section-height-default" data-id="3a021c1" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-b5239ed" data-id="b5239ed" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-b04fa07 elementor-widget__width-auto elementor-widget elementor-widget-image" data-id="b04fa07" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img decoding="async" src="/images/about/aldi-sigun-K-sdQ12jZeY-unsplash-1-pqla1sedpr50vgaxs1zuit50i9ep8iuvk4mn5xgmro.jpg" title="aldi-sigun-K-sdQ12jZeY-unsplash 1" alt="aldi-sigun-K-sdQ12jZeY-unsplash 1" class="elementor-animation-shrink" loading="lazy">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-f64d1be" data-id="f64d1be" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-4bcd901 elementor-widget elementor-widget-heading" data-id="4bcd901" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Thomas Rodriguez</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-7525039 elementor-widget elementor-widget-heading" data-id="7525039" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">Developer</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-0da80a6 elementor-widget elementor-widget-text-editor" data-id="0da80a6" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Vel eros donec ac odio tempor orci dapibus ultrices.								</div>
				</div>
				<div class="elementor-element elementor-element-5d1d884 elementor-grid-3 e-grid-align-left e-grid-align-mobile-center elementor-shape-rounded elementor-widget elementor-widget-social-icons" data-id="5d1d884" data-element_type="widget" data-e-type="widget" data-widget_type="social-icons.default">
				<div class="elementor-widget-container">
							<div class="elementor-social-icons-wrapper elementor-grid" role="list">
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-twitter elementor-repeater-item-05be2cd" target="_blank">
						<span class="elementor-screen-only">Twitter</span>
						<i aria-hidden="true" class="fab fa-twitter"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-facebook-f elementor-repeater-item-5498b4f" target="_blank">
						<span class="elementor-screen-only">Facebook-f</span>
						<i aria-hidden="true" class="fab fa-facebook-f"></i>					</a>
				</span>
							<span class="elementor-grid-item" role="listitem">
					<a class="elementor-icon elementor-social-icon elementor-social-icon-instagram elementor-repeater-item-418ce82" target="_blank">
						<span class="elementor-screen-only">Instagram</span>
						<i aria-hidden="true" class="fab fa-instagram"></i>					</a>
				</span>
					</div>
						</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-0619496 elementor-section-content-middle elementor-hidden-desktop elementor-hidden-tablet elementor-section-boxed elementor-section-height-default" data-id="0619496" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-819fb1c" data-id="819fb1c" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-16c8a35 elementor-align-right elementor-mobile-align-justify elementor-widget elementor-widget-button" data-id="16c8a35" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation_mobile&quot;:&quot;fadeInUp&quot;}" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/about#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">View all team</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-0b16851 elementor-section-content-middle elementor-hidden-tablet elementor-hidden-mobile elementor-section-boxed elementor-section-height-default" data-id="0b16851" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-e66aacd" data-id="e66aacd" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-11ea93f elementor-widget elementor-widget-heading" data-id="11ea93f" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">🔥🔥🔥<br>
Create, sell and collect<br>
NFT digital assests</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-afcdd2b elementor-widget elementor-widget-text-editor" data-id="afcdd2b" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Buy and sell over 100 cryptocurrencies in the marketplace over 20 fixed currencies using bank transfers or credit/debit cards.								</div>
				</div>
				<div class="elementor-element elementor-element-e05fe2b elementor-align-left elementor-tablet-align-center elementor-mobile-align-justify elementor-invisible elementor-widget elementor-widget-button" data-id="e05fe2b" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInUp&quot;}" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/about#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Create NFT</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-78ebfe6" data-id="78ebfe6" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-581fdf8 elementor-section-content-middle elementor-section-boxed elementor-section-height-default" data-id="581fdf8" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-2c228c1" data-id="2c228c1" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-9d6c29d elementor-invisible elementor-widget elementor-widget-image" data-id="9d6c29d" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInDown&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="156" height="156" src="/images/about/img-1.png" class="attachment-medium size-medium wp-image-919" alt="" sizes="(max-width: 156px) 100vw, 156px">															</div>
				</div>
				<div class="elementor-element elementor-element-0e42577 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-invisible elementor-widget elementor-widget-image" data-id="0e42577" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInLeft&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="230" height="280" src="/images/about/img-4.png" class="attachment-medium_large size-medium_large wp-image-922" alt="">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-4ba799b" data-id="4ba799b" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-75c9506 elementor-widget__width-auto elementor-invisible elementor-widget elementor-widget-image" data-id="75c9506" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInRight&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="460" height="560" src="/images/about/img@2x.jpg" class="attachment-medium_large size-medium_large wp-image-5067" alt="" sizes="(max-width: 460px) 100vw, 460px">															</div>
				</div>
				<div class="elementor-element elementor-element-4c94d0e elementor-invisible elementor-widget elementor-widget-image" data-id="4c94d0e" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInUp&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="390" height="156" src="/images/about/img-3.png" class="attachment-full size-full wp-image-921" alt="" sizes="(max-width: 390px) 100vw, 390px">															</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				<section class="elementor-section elementor-top-section elementor-element elementor-element-cec11fe elementor-section-content-middle elementor-hidden-desktop elementor-section-boxed elementor-section-height-default" data-id="cec11fe" data-element_type="section" data-e-type="section" data-settings="{&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-0207e49" data-id="0207e49" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;gradient&quot;,&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-7b93936 elementor-widget elementor-widget-heading" data-id="7b93936" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
					<h3 class="elementor-heading-title elementor-size-default">🔥🔥🔥<br>
Create, sell and collect<br>
NFT digital assests</h3>				</div>
				</div>
				<div class="elementor-element elementor-element-6368ee3 elementor-widget elementor-widget-text-editor" data-id="6368ee3" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
									Buy and sell over 100 cryptocurrencies in the marketplace over 20 fixed currencies using bank transfers or credit/debit cards.								</div>
				</div>
				<div class="elementor-element elementor-element-15dec81 elementor-align-left elementor-tablet-align-center elementor-mobile-align-justify elementor-invisible elementor-widget elementor-widget-button" data-id="15dec81" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInUp&quot;}" data-widget_type="button.default">
				<div class="elementor-widget-container">
									<div class="elementor-button-wrapper">
					<a class="elementor-button elementor-button-link elementor-size-sm elementor-animation-push" href="/about#">
						<span class="elementor-button-content-wrapper">
									<span class="elementor-button-text">Create NFT</span>
					</span>
					</a>
				</div>
								</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-6e35843" data-id="6e35843" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<section class="elementor-section elementor-inner-section elementor-element elementor-element-4724d07 elementor-section-content-middle elementor-hidden-mobile elementor-section-boxed elementor-section-height-default" data-id="4724d07" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;gradient&quot;,&quot;mdp_selection_sticky_effect_enable&quot;:false}">
						<div class="elementor-container elementor-column-gap-no">
					<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-0640d65" data-id="0640d65" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-60e9ee4 elementor-invisible elementor-widget elementor-widget-image" data-id="60e9ee4" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInDown&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="156" height="156" src="/images/about/img-1.png" class="attachment-medium size-medium wp-image-919" alt="" sizes="(max-width: 156px) 100vw, 156px">															</div>
				</div>
				<div class="elementor-element elementor-element-268dbc8 elementor-widget__width-auto elementor-widget-mobile__width-inherit elementor-invisible elementor-widget elementor-widget-image" data-id="268dbc8" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInLeft&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="230" height="280" src="/images/about/img-4.png" class="attachment-medium_large size-medium_large wp-image-922" alt="">															</div>
				</div>
					</div>
		</div>
				<div class="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-e85c875" data-id="e85c875" data-element_type="column" data-e-type="column" data-settings="{&quot;mdp_selection_sticky_column_effect_enable&quot;:false}">
			<div class="elementor-widget-wrap elementor-element-populated">
						<div class="elementor-element elementor-element-96916eb elementor-widget__width-auto elementor-invisible elementor-widget elementor-widget-image" data-id="96916eb" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInRight&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="460" height="560" src="/images/about/img@2x.jpg" class="attachment-medium_large size-medium_large wp-image-5067" alt="" sizes="(max-width: 460px) 100vw, 460px">															</div>
				</div>
				<div class="elementor-element elementor-element-7896940 elementor-invisible elementor-widget elementor-widget-image" data-id="7896940" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInUp&quot;}" data-widget_type="image.default">
				<div class="elementor-widget-container">
															<img loading="lazy" decoding="async" width="390" height="156" src="/images/about/img-3.png" class="attachment-full size-full wp-image-921" alt="" sizes="(max-width: 390px) 100vw, 390px">															</div>
				</div>
					</div>
		</div>
					</div>
		</section>
					</div>
		</div>
					</div>
		</section>
				</div>
		
		
			</div>

	
</main>

			`;
