// Collect <script> tags (both src= and inline) from the source HTML pages in
// source order. Inline configs like `var elementorFrontendConfig = {...}`
// must run BEFORE the matching src bundle, so order matters. Output is one
// HTML snippet appended just before </body>.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const OUT = join(__dirname, '..', 'src', 'fragments', 'scripts-head.js');

// We mine index.html for the canonical script order (its head + body cover
// the widest set of scripts). Other pages append any extras we haven't seen.
const PRIORITY = ['index.html', 'home-2.html', 'about.html', 'blog.html', 'shop.html', 'product.html', 'contacts.html', 'authors.html', 'login.html', '404.html'];
const allHtml = readdirSync(ROOT).filter((f) => f.endsWith('.html'));
const ordered = [...new Set([...PRIORITY.filter((f) => allHtml.includes(f)), ...allHtml])];

const tagRegex = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;

const out = [];
const seenSrc = new Set();
const seenInlineHash = new Set();

function rewriteSrc(src) {
  if (/^https?:|^chrome-extension:|^data:/i.test(src)) return null;
  if (src.startsWith('js/')) return '/' + src;
  if (src.startsWith('/')) return src;
  return null;
}

function unmojibakeBlock(s) {
  // Inline scripts may contain mojibake'd strings. Try per-line cp1252 -> utf8.
  return s.split('\n').map((line) => {
    const bytes = [];
    let ok = true;
    for (const ch of line) {
      const cp = ch.codePointAt(0);
      if (cp <= 0x7F || (cp >= 0xA0 && cp <= 0xFF)) bytes.push(cp);
      else if (cp === 0x20AC) bytes.push(0x80);
      else if (cp === 0x2019) bytes.push(0x92);
      else if (cp === 0x2018) bytes.push(0x91);
      else if (cp === 0x201D) bytes.push(0x94);
      else if (cp === 0x201C) bytes.push(0x93);
      else if (cp === 0x2013) bytes.push(0x96);
      else if (cp === 0x2014) bytes.push(0x97);
      else if (cp === 0x0178) bytes.push(0x9F);
      else { ok = false; break; }
    }
    if (!ok) return line;
    const buf = Buffer.from(bytes);
    const decoded = buf.toString('utf8');
    if (decoded.includes('�')) return line;
    return decoded;
  }).join('\n');
}

for (const file of ordered) {
  const html = readFileSync(join(ROOT, file), 'utf8');
  for (const match of html.matchAll(tagRegex)) {
    const attrs = match[1];
    const body = match[2];

    // Skip prefetch / speculation rules scripts
    if (/type=["']speculationrules["']|type=["']application\/ld\+json["']/i.test(attrs)) continue;

    const srcMatch = attrs.match(/\bsrc\s*=\s*"([^"]+)"/i);
    if (srcMatch) {
      const fixed = rewriteSrc(srcMatch[1].trim());
      if (!fixed) continue;
      if (seenSrc.has(fixed)) continue;
      seenSrc.add(fixed);
      out.push(`<script src="${fixed}"></script>`);
    } else if (body && body.trim()) {
      // Inline script. Skip noise like rocket_lcp_data tracking.
      if (/rocket_lcp_data|wpr-lcp-beacon|lazyloadRunObserver/i.test(body)) {
        // Keep lazyloadRunObserver — needed for backgrounds
        if (!/lazyloadRunObserver/.test(body)) continue;
      }
      const cleaned = unmojibakeBlock(body);
      const hash = createHash('sha1').update(cleaned).digest('hex');
      if (seenInlineHash.has(hash)) continue;
      seenInlineHash.add(hash);
      out.push(`<script>${cleaned}</script>`);
    }
  }
}

const tags = out.join('\n');
const safe = tags.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
writeFileSync(
  OUT,
  '// Auto-generated by scripts/collect-scripts.mjs - do not edit by hand.\nexport default `' + safe + '`;\n',
  'utf8'
);
console.log(`Collected ${out.length} script tags (${seenSrc.size} src, ${seenInlineHash.size} inline)`);
console.log(`Wrote ${OUT}`);
