// Walks every source HTML page and collects:
//   1. every <link rel="stylesheet" href="..."> (deduped, source order preserved)
//   2. every <style ...>...</style> block (deduped by content hash)
// then writes them into xchain-app/src/fragments/styles-head.js as a single
// HTML snippet we can inject into <head> at runtime.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const OUT = join(__dirname, '..', 'src', 'fragments', 'styles-head.js');

const CP1252_EXTRAS = new Map([
  [0x20AC, 0x80], [0x201A, 0x82], [0x0192, 0x83], [0x201E, 0x84],
  [0x2026, 0x85], [0x2020, 0x86], [0x2021, 0x87], [0x02C6, 0x88],
  [0x2030, 0x89], [0x0160, 0x8A], [0x2039, 0x8B], [0x0152, 0x8C],
  [0x017D, 0x8E], [0x2018, 0x91], [0x2019, 0x92], [0x201C, 0x93],
  [0x201D, 0x94], [0x2022, 0x95], [0x2013, 0x96], [0x2014, 0x97],
  [0x02DC, 0x98], [0x2122, 0x99], [0x0161, 0x9A], [0x203A, 0x9B],
  [0x0153, 0x9C], [0x017E, 0x9E], [0x0178, 0x9F]
]);

function toCp1252Bytes(str) {
  const out = [];
  for (const ch of str) {
    const cp = ch.codePointAt(0);
    if (cp <= 0x7F || (cp >= 0xA0 && cp <= 0xFF)) {
      out.push(cp);
    } else if (CP1252_EXTRAS.has(cp)) {
      out.push(CP1252_EXTRAS.get(cp));
    } else {
      return null;
    }
  }
  return Buffer.from(out);
}

function unmojibake(s) {
  return s.split('\n').map((line) => {
    const bytes = toCp1252Bytes(line);
    if (!bytes) return line;
    const decoded = bytes.toString('utf8');
    if (decoded.includes('�')) return line;
    return decoded;
  }).join('\n');
}

const HTML_FILES = readdirSync(ROOT).filter((f) => f.endsWith('.html'));

const linkRegex = /<link\b[^>]*\brel\s*=\s*"stylesheet"[^>]*>/gi;
const styleRegex = /<style\b[^>]*>[\s\S]*?<\/style>/gi;

const links = new Map();    // href -> full tag
const styles = new Map();   // hash -> full tag

function rewriteHref(tag) {
  return tag.replace(/\b(href)\s*=\s*"([^"]*)"/i, (m, attr, val) => {
    if (/^(https?:|data:|\/)/i.test(val)) return `${attr}="${val}"`;
    if (val.startsWith('css/')) return `${attr}="/${val}"`;
    return `${attr}="${val}"`;
  });
}

function rewriteUrlInStyleBody(tag) {
  // Rewrite url(...) inside the <style> body so relative refs resolve from root
  return tag.replace(/url\(\s*(['"]?)([^'")]+)\1\s*\)/g, (m, q, val) => {
    if (/^(https?:|data:|\/)/i.test(val)) return m;
    if (/^(css|js|images|fonts|webfonts|maps)\//.test(val)) {
      return `url(${q}/${val}${q})`;
    }
    return m;
  });
}

for (const file of HTML_FILES) {
  const html = unmojibake(readFileSync(join(ROOT, file), 'utf8'));

  for (const match of html.matchAll(linkRegex)) {
    const tag = match[0];
    const hrefMatch = tag.match(/\bhref\s*=\s*"([^"]+)"/i);
    if (!hrefMatch) continue;
    const href = hrefMatch[1];
    // skip chrome-extension and similar
    if (/^chrome-extension:/i.test(href)) continue;
    if (!links.has(href)) {
      links.set(href, rewriteHref(tag));
    }
  }

  for (const match of html.matchAll(styleRegex)) {
    const tag = match[0];
    const rewritten = rewriteUrlInStyleBody(tag);
    const hash = createHash('sha1').update(rewritten).digest('hex');
    if (!styles.has(hash)) {
      styles.set(hash, rewritten);
    }
  }
}

const headHtml = [
  '<!-- auto-generated styles aggregated from all source HTML pages -->',
  ...links.values(),
  ...styles.values()
].join('\n');

const safe = headHtml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
writeFileSync(
  OUT,
  `// Auto-generated by scripts/collect-styles.mjs — do not edit by hand.\nexport default \`${safe}\`;\n`,
  'utf8'
);

console.log(`Collected ${links.size} stylesheets and ${styles.size} <style> blocks`);
console.log(`Wrote ${OUT}`);
