// Collect every <script src="..."> reference from all source HTML pages, in
// the order they first appear. Inline <script> blocks are skipped — they're
// mostly per-element Elementor init that the frontend bundle reinitializes on
// its own once it boots. Output is consumed by vite.config.js to inject a
// single ordered list of <script> tags into index.html.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const OUT = join(__dirname, '..', 'src', 'fragments', 'scripts-head.js');

const HTML_FILES = readdirSync(ROOT).filter((f) => f.endsWith('.html'));

// First-appearance order
const seen = new Set();
const ordered = [];

const scriptRegex = /<script\b[^>]*\bsrc\s*=\s*"([^"]+)"[^>]*>\s*<\/script>/gi;

for (const file of HTML_FILES) {
  const html = readFileSync(join(ROOT, file), 'utf8');
  for (const match of html.matchAll(scriptRegex)) {
    let src = match[1].trim();
    if (/^chrome-extension:/i.test(src)) continue;
    if (/^https?:/i.test(src)) continue;
    if (/^data:/i.test(src)) continue;
    if (src.startsWith('js/')) src = '/' + src;
    if (!seen.has(src)) {
      seen.add(src);
      ordered.push(src);
    }
  }
}

const tags = ordered.map((src) => `<script src="${src}"></script>`).join('\n');
const safe = tags.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
writeFileSync(
  OUT,
  '// Auto-generated by scripts/collect-scripts.mjs - do not edit by hand.\nexport default `' + safe + '`;\n',
  'utf8'
);
console.log(`Collected ${ordered.length} script srcs`);
console.log(`Wrote ${OUT}`);
